version: '3.8'

# Relies on secrets.env containing
#  - POSTGRES_PASSWORD
#  - OIDC_RP_CLIENT_ID
#  - OIDC_RP_CLIENT_SECRET
#
services:
  db:
    image: postgres:14
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_DB=rpctools
      - POSTGRES_USER=rpc
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_HOST_AUTH_METHOD=trust

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    <<: &default
      image: rpc-app
    command: sleep infinity
    volumes:
      - .:/workspace
      - /workspace/__pycache__
    env_file:
      - secrets.env
    environment:
      - POSTGRES_DB=rpctools
      - POSTGRES_USER=rpc
      - POSTGRES_PASSWORD=abcd1234
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  client:
    <<: *default
    command: sleep infinity
    volumes:
      - .:/workspace

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - app
      - client
      - pgadmin

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
        - PGADMIN_DEFAULT_EMAIL=dev@ietf.org
        - PGADMIN_DEFAULT_PASSWORD=dev
        - PGADMIN_CONFIG_LOGIN_BANNER="Login with dev@ietf.org / dev"
        - PGADMIN_DISABLE_POSTFIX=True
        - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
        - SCRIPT_NAME=/pgadmin
    volumes:
        - ./docker/configs/pgadmin-servers.json:/pgadmin4/servers.json

volumes:
  postgresdb-data:
