#!/bin/bash

mkdir holdme
mkdir holdme/rpc
mkdir holdme/datatracker
if ! [ -x /home/dev/.local/bin/ruff ]; then pip install ruff; fi
grep -rl RunPython rpc/migrations | xargs mv -t holdme/rpc
rm rpc/migrations/0*.py
sed -i 's/("rpc", "0001_initial"),/#("rpc", "0001_initial"),/' datatracker/migrations/0002_initial.py
./manage.py makemigrations rpc
ruff format rpc
sed -i 's/#("rpc", "0001_initial"),/("rpc", "0001_initial"),/' datatracker/migrations/0002_initial.py
mv datatracker/migrations/000[23456789]*py holdme/datatracker
sed -i 's/("datatracker", "0.*$/#("datatracker", "0001_initial"),/' rpc/migrations/0001_initial.py
sed -i 's/label = models.ForeignKey("rpc.Label", on_delete=models.PROTECT)/#label = models.ForeignKey("rpc.Label", on_delete=models.PROTECT)/' datatracker/models.py
sed -i 's/labels = models.ManyToManyField("rpc.Label", through="DocumentLabel")/#labels = models.ManyToManyField("rpc.Label", through="DocumentLabel")/' datatracker/models.py
rm datatracker/migrations/0*.py
./manage.py makemigrations datatracker
sed -i 's/#label = models.ForeignKey("rpc.Label", on_delete=models.PROTECT)/label = models.ForeignKey("rpc.Label", on_delete=models.PROTECT)/' datatracker/models.py
sed -i 's/#labels = models.ManyToManyField("rpc.Label", through="DocumentLabel")/labels = models.ManyToManyField("rpc.Label", through="DocumentLabel")/' datatracker/models.py
mv holdme/datatracker/*py datatracker/migrations/
sed -i 's/#("datatracker", "0001_initial"),/("datatracker", "0001_initial"),/' rpc/migrations/0001_initial.py
ruff format datatracker
sed -i 's/("datatracker", "0003_document_intended_std_level")/("datatracker", "0001_initial")/' rpc/migrations/0001_initial.py
sed -i 's/# Generated by .*$/# Copyright The IETF Trust 2025-2026, All Rights Reserved/' rpc/migrations/0001_initial.py
sed -i 's/# Generated by .*$/# Copyright The IETF Trust 2025-2026, All Rights Reserved/' datatracker/migrations/0001_initial.py
mv holdme/rpc/*py rpc/migrations/
ruff format rpc datatracker
rm -r holdme
ruff check --fix .
echo "Inspect, and if necessary rename data migrations and update their dependencies"
