#!/bin/bash

mkdir holdme
mkdir holdme/rpc
mkdir holdme/datatracker
mkdir holdme/errata
if ! [ -x /home/dev/.local/bin/ruff ]; then pip install ruff; fi
# The next two lines require maintenance if more data migrations are added
mv rpc/migrations/000[234]*py holdme/rpc
rm rpc/migrations/000[156789]*.py
sed -i 's/("rpc", "0001_initial"),/#("rpc", "0001_initial"),/' datatracker/migrations/0002_initial.py
sed -i 's/("rpc", "0004_populate_capability"),/#("rpc", "0004_populate_capability"),/' errata/migrations/0001_initial.py
./manage.py makemigrations rpc
ruff format rpc
sed -i 's/#("rpc", "0001_initial"),/("rpc", "0001_initial"),/' datatracker/migrations/0002_initial.py
mv datatracker/migrations/0002*py holdme/datatracker
mv errata/migrations/000[23456789]*py holdme/errata/
sed -i 's/("datatracker", "0.*$/#("datatracker", "0002_initial"),/' errata/migrations/0001_initial.py
sed -i 's/("datatracker", "0.*$/#("datatracker", "0001_initial"),/' rpc/migrations/0001_initial.py
sed -i 's/label = models.ForeignKey("rpc.Label", on_delete=models.PROTECT)/#label = models.ForeignKey("rpc.Label", on_delete=models.PROTECT)/' datatracker/models.py
sed -i 's/labels = models.ManyToManyField("rpc.Label", through="DocumentLabel")/#labels = models.ManyToManyField("rpc.Label", through="DocumentLabel")/' datatracker/models.py
rm datatracker/migrations/0*.py
./manage.py makemigrations datatracker
rm errata/migrations/0001_initial.py
./manage.py makemigrations errata
sed -i 's/#label = models.ForeignKey("rpc.Label", on_delete=models.PROTECT)/label = models.ForeignKey("rpc.Label", on_delete=models.PROTECT)/' datatracker/models.py
sed -i 's/#labels = models.ManyToManyField("rpc.Label", through="DocumentLabel")/labels = models.ManyToManyField("rpc.Label", through="DocumentLabel")/' datatracker/models.py
mv holdme/datatracker/*py datatracker/migrations/
sed -i 's/#("datatracker", "0002_initial"),/("datatracker", "0002_initial"),/' errata/migrations/0001_initial.py
sed -i 's/#("datatracker", "0001_initial"),/("datatracker", "0001_initial"),/' rpc/migrations/0001_initial.py
ruff format datatracker
sed -i 's/#("rpc", "0004_populate_capability"),/("rpc", "0004_populate_capability"),/' errata/migrations/0001_initial.py
sed -i 's/("datatracker", "0003_document_intended_std_level")/("datatracker", "0001_initial")/' rpc/migrations/0001_initial.py
sed -i 's/# Generated by .*$/# Copyright The IETF Trust 2025, All Rights Reserved/' rpc/migrations/0001_initial.py
sed -i 's/# Generated by .*$/# Copyright The IETF Trust 2025, All Rights Reserved/' datatracker/migrations/0001_initial.py
sed -i 's/# Generated by .*$/# Copyright The IETF Trust 2025, All Rights Reserved/' errata/migrations/0001_initial.py
mv holdme/rpc/*py rpc/migrations/
mv holdme/errata/* errata/migrations/
ruff format rpc datatracker errata
rm -r holdme
