namespace: purple
configMapGenerator:
  - name: purple-files-cfgmap
    files:
      - nginx-logging.conf
      - nginx-purple.conf
resources:
  - beat.yaml
  - celery.yaml
  - memcached.yaml
  - purple.yaml
