# Generated by Django 5.2.1 on 2025-05-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpc", "0004_populate_capability"),
    ]

    operations = [
        migrations.AddField(
            model_name="rpcperson",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
