# Generated by Django 5.2.1 on 2025-05-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpc", "0005_approvallogmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallabel",
            name="is_complexity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="label",
            name="is_complexity",
            field=models.BooleanField(default=False),
        ),
    ]
