# Generated by Django 5.2.3 on 2025-08-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datatracker", "0002_initial"),
        ("rpc", "0008_add_ref_checker_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionholder",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actionholder",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actionholder",
            name="target_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actionholder_set",
                to="datatracker.document",
            ),
        ),
        migrations.AlterField(
            model_name="actionholder",
            name="target_rfctobe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actionholder_set",
                to="rpc.rfctobe",
            ),
        ),
        migrations.AlterField(
            model_name="finalapproval",
            name="approved",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="finalapproval",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approver_set",
                to="datatracker.datatrackerperson",
            ),
        ),
        migrations.AlterField(
            model_name="finalapproval",
            name="overriding_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="overriding_approver_set",
                to="datatracker.datatrackerperson",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrfctobe",
            name="external_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalrfctobe",
            name="internal_goal",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalrfctobe",
            name="rfc_number",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="rfcauthor",
            name="datatracker_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="datatracker.datatrackerperson",
            ),
        ),
        migrations.AlterField(
            model_name="rfctobe",
            name="draft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="datatracker.document",
            ),
        ),
        migrations.AlterField(
            model_name="rfctobe",
            name="external_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rfctobe",
            name="internal_goal",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rfctobe",
            name="rfc_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
