/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize an ActionHolder with person name
 * @export
 * @interface ActionHolderRequest
 */
export interface ActionHolderRequest {
    /**
     * 
     * @type {Date}
     * @memberof ActionHolderRequest
     */
    deadline?: Date | null;
    /**
     * The action is considered done when the completed field is set with a datetime.
     * @type {Date}
     * @memberof ActionHolderRequest
     */
    completed?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ActionHolderRequest
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof ActionHolderRequest
     */
    body?: string;
}

/**
 * Check if a given object implements the ActionHolderRequest interface.
 */
export function instanceOfActionHolderRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ActionHolderRequestFromJSON(json: any): ActionHolderRequest {
    return ActionHolderRequestFromJSONTyped(json, false);
}

export function ActionHolderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionHolderRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deadline': !exists(json, 'deadline') ? undefined : (json['deadline'] === null ? null : new Date(json['deadline'])),
        'completed': !exists(json, 'completed') ? undefined : (json['completed'] === null ? null : new Date(json['completed'])),
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'body': !exists(json, 'body') ? undefined : json['body'],
    };
}

export function ActionHolderRequestToJSON(value?: ActionHolderRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deadline': value.deadline === undefined ? undefined : (value.deadline === null ? null : value.deadline.toISOString()),
        'completed': value.completed === undefined ? undefined : (value.completed === null ? null : value.completed.toISOString()),
        'comment': value.comment,
        'body': value.body,
    };
}

