/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize an ActionHolder with person name
 * @export
 * @interface ActionHolder
 */
export interface ActionHolder {
    /**
     * 
     * @type {number}
     * @memberof ActionHolder
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof ActionHolder
     */
    readonly name?: string;
    /**
     * 
     * @type {Date}
     * @memberof ActionHolder
     */
    deadline?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ActionHolder
     */
    readonly sinceWhen?: Date;
    /**
     * The action is considered done when the completed field is set with a datetime.
     * @type {Date}
     * @memberof ActionHolder
     */
    completed?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ActionHolder
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof ActionHolder
     */
    body?: string;
}

/**
 * Check if a given object implements the ActionHolder interface.
 */
export function instanceOfActionHolder(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ActionHolderFromJSON(json: any): ActionHolder {
    return ActionHolderFromJSONTyped(json, false);
}

export function ActionHolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionHolder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'deadline': !exists(json, 'deadline') ? undefined : (json['deadline'] === null ? null : new Date(json['deadline'])),
        'sinceWhen': !exists(json, 'since_when') ? undefined : (new Date(json['since_when'])),
        'completed': !exists(json, 'completed') ? undefined : (json['completed'] === null ? null : new Date(json['completed'])),
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'body': !exists(json, 'body') ? undefined : json['body'],
    };
}

export function ActionHolderToJSON(value?: ActionHolder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deadline': value.deadline === undefined ? undefined : (value.deadline === null ? null : value.deadline.toISOString()),
        'completed': value.completed === undefined ? undefined : (value.completed === null ? null : value.completed.toISOString()),
        'comment': value.comment,
        'body': value.body,
    };
}

