/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DatatrackerPerson } from './DatatrackerPerson';
import {
    DatatrackerPersonFromJSON,
    DatatrackerPersonFromJSONTyped,
    DatatrackerPersonToJSON,
} from './DatatrackerPerson';
import type { MinimalRfcToBe } from './MinimalRfcToBe';
import {
    MinimalRfcToBeFromJSON,
    MinimalRfcToBeFromJSONTyped,
    MinimalRfcToBeToJSON,
} from './MinimalRfcToBe';

/**
 * 
 * @export
 * @interface ApprovalLogMessage
 */
export interface ApprovalLogMessage {
    /**
     * 
     * @type {number}
     * @memberof ApprovalLogMessage
     */
    readonly id?: number;
    /**
     * 
     * @type {DatatrackerPerson}
     * @memberof ApprovalLogMessage
     */
    readonly by?: DatatrackerPerson;
    /**
     * 
     * @type {MinimalRfcToBe}
     * @memberof ApprovalLogMessage
     */
    readonly rfcToBe?: MinimalRfcToBe;
    /**
     * 
     * @type {string}
     * @memberof ApprovalLogMessage
     */
    logMessage: string;
    /**
     * 
     * @type {Date}
     * @memberof ApprovalLogMessage
     */
    readonly time?: Date;
}

/**
 * Check if a given object implements the ApprovalLogMessage interface.
 */
export function instanceOfApprovalLogMessage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "logMessage" in value;

    return isInstance;
}

export function ApprovalLogMessageFromJSON(json: any): ApprovalLogMessage {
    return ApprovalLogMessageFromJSONTyped(json, false);
}

export function ApprovalLogMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovalLogMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'by': !exists(json, 'by') ? undefined : DatatrackerPersonFromJSON(json['by']),
        'rfcToBe': !exists(json, 'rfc_to_be') ? undefined : MinimalRfcToBeFromJSON(json['rfc_to_be']),
        'logMessage': json['log_message'],
        'time': !exists(json, 'time') ? undefined : (new Date(json['time'])),
    };
}

export function ApprovalLogMessageToJSON(value?: ApprovalLogMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'log_message': value.logMessage,
    };
}

