/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApprovalLogMessageRequest
 */
export interface ApprovalLogMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof ApprovalLogMessageRequest
     */
    logMessage: string;
}

/**
 * Check if a given object implements the ApprovalLogMessageRequest interface.
 */
export function instanceOfApprovalLogMessageRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "logMessage" in value;

    return isInstance;
}

export function ApprovalLogMessageRequestFromJSON(json: any): ApprovalLogMessageRequest {
    return ApprovalLogMessageRequestFromJSONTyped(json, false);
}

export function ApprovalLogMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovalLogMessageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'logMessage': json['log_message'],
    };
}

export function ApprovalLogMessageRequestToJSON(value?: ApprovalLogMessageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'log_message': value.logMessage,
    };
}

