/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StateEnum } from './StateEnum';
import {
    StateEnumFromJSON,
    StateEnumFromJSONTyped,
    StateEnumToJSON,
} from './StateEnum';

/**
 * Assignment serializer with PK reference to RfcToBe
 * @export
 * @interface Assignment
 */
export interface Assignment {
    /**
     * 
     * @type {number}
     * @memberof Assignment
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof Assignment
     */
    rfcToBe: number;
    /**
     * 
     * @type {number}
     * @memberof Assignment
     */
    person?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Assignment
     */
    role: string;
    /**
     * 
     * @type {StateEnum}
     * @memberof Assignment
     */
    state?: StateEnum;
    /**
     * 
     * @type {string}
     * @memberof Assignment
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof Assignment
     */
    timeSpent?: string;
}

/**
 * Check if a given object implements the Assignment interface.
 */
export function instanceOfAssignment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rfcToBe" in value;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function AssignmentFromJSON(json: any): Assignment {
    return AssignmentFromJSONTyped(json, false);
}

export function AssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Assignment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'rfcToBe': json['rfc_to_be'],
        'person': !exists(json, 'person') ? undefined : json['person'],
        'role': json['role'],
        'state': !exists(json, 'state') ? undefined : StateEnumFromJSON(json['state']),
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'timeSpent': !exists(json, 'time_spent') ? undefined : json['time_spent'],
    };
}

export function AssignmentToJSON(value?: Assignment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rfc_to_be': value.rfcToBe,
        'person': value.person,
        'role': value.role,
        'state': StateEnumToJSON(value.state),
        'comment': value.comment,
        'time_spent': value.timeSpent,
    };
}

