/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorOrderStatus
 */
export interface AuthorOrderStatus {
    /**
     * Status message
     * @type {string}
     * @memberof AuthorOrderStatus
     */
    status: string;
}

/**
 * Check if a given object implements the AuthorOrderStatus interface.
 */
export function instanceOfAuthorOrderStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function AuthorOrderStatusFromJSON(json: any): AuthorOrderStatus {
    return AuthorOrderStatusFromJSONTyped(json, false);
}

export function AuthorOrderStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorOrderStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function AuthorOrderStatusToJSON(value?: AuthorOrderStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

