/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorOrder
 */
export interface AuthorOrder {
    /**
     * List of RfcAuthor IDs in the desired order
     * @type {Array<number>}
     * @memberof AuthorOrder
     */
    order: Array<number>;
}

/**
 * Check if a given object implements the AuthorOrder interface.
 */
export function instanceOfAuthorOrder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "order" in value;

    return isInstance;
}

export function AuthorOrderFromJSON(json: any): AuthorOrder {
    return AuthorOrderFromJSONTyped(json, false);
}

export function AuthorOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'order': json['order'],
    };
}

export function AuthorOrderToJSON(value?: AuthorOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order': value.order,
    };
}

