/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a minimal DatatrackerPerson
 * 
 * This is the serializer to use if you may be working with non-persisted
 * DatatrackerPerson instances.
 * @export
 * @interface BaseDatatrackerPerson
 */
export interface BaseDatatrackerPerson {
    /**
     * 
     * @type {number}
     * @memberof BaseDatatrackerPerson
     */
    personId: number;
    /**
     * 
     * @type {string}
     * @memberof BaseDatatrackerPerson
     */
    readonly name?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseDatatrackerPerson
     */
    readonly email?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseDatatrackerPerson
     */
    readonly picture?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseDatatrackerPerson
     */
    readonly datatrackerUrl?: string;
}

/**
 * Check if a given object implements the BaseDatatrackerPerson interface.
 */
export function instanceOfBaseDatatrackerPerson(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "personId" in value;

    return isInstance;
}

export function BaseDatatrackerPersonFromJSON(json: any): BaseDatatrackerPerson {
    return BaseDatatrackerPersonFromJSONTyped(json, false);
}

export function BaseDatatrackerPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseDatatrackerPerson {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'personId': json['person_id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'picture': !exists(json, 'picture') ? undefined : json['picture'],
        'datatrackerUrl': !exists(json, 'datatracker_url') ? undefined : json['datatracker_url'],
    };
}

export function BaseDatatrackerPersonToJSON(value?: BaseDatatrackerPerson | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'person_id': value.personId,
    };
}

