/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a minimal DatatrackerPerson
 * 
 * This is the serializer to use if you may be working with non-persisted
 * DatatrackerPerson instances.
 * @export
 * @interface BaseDatatrackerPersonRequest
 */
export interface BaseDatatrackerPersonRequest {
    /**
     * 
     * @type {number}
     * @memberof BaseDatatrackerPersonRequest
     */
    personId: number;
}

/**
 * Check if a given object implements the BaseDatatrackerPersonRequest interface.
 */
export function instanceOfBaseDatatrackerPersonRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "personId" in value;

    return isInstance;
}

export function BaseDatatrackerPersonRequestFromJSON(json: any): BaseDatatrackerPersonRequest {
    return BaseDatatrackerPersonRequestFromJSONTyped(json, false);
}

export function BaseDatatrackerPersonRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseDatatrackerPersonRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'personId': json['person_id'],
    };
}

export function BaseDatatrackerPersonRequestToJSON(value?: BaseDatatrackerPersonRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'person_id': value.personId,
    };
}

