/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Capability
 */
export interface Capability {
    /**
     * 
     * @type {string}
     * @memberof Capability
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof Capability
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Capability
     */
    desc?: string;
}

/**
 * Check if a given object implements the Capability interface.
 */
export function instanceOfCapability(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CapabilityFromJSON(json: any): Capability {
    return CapabilityFromJSONTyped(json, false);
}

export function CapabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Capability {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'name': json['name'],
        'desc': !exists(json, 'desc') ? undefined : json['desc'],
    };
}

export function CapabilityToJSON(value?: Capability | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
        'desc': value.desc,
    };
}

