/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for reordering documents in a cluster
 * @export
 * @interface ClusterReorderDocumentsRequest
 */
export interface ClusterReorderDocumentsRequest {
    /**
     * List of draft names in the desired order
     * @type {Array<string>}
     * @memberof ClusterReorderDocumentsRequest
     */
    draftNames: Array<string>;
}

/**
 * Check if a given object implements the ClusterReorderDocumentsRequest interface.
 */
export function instanceOfClusterReorderDocumentsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "draftNames" in value;

    return isInstance;
}

export function ClusterReorderDocumentsRequestFromJSON(json: any): ClusterReorderDocumentsRequest {
    return ClusterReorderDocumentsRequestFromJSONTyped(json, false);
}

export function ClusterReorderDocumentsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterReorderDocumentsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'draftNames': json['draft_names'],
    };
}

export function ClusterReorderDocumentsRequestToJSON(value?: ClusterReorderDocumentsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'draft_names': value.draftNames,
    };
}

