/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for adding or removing a document in a cluster
 * @export
 * @interface ClusterAddRemoveDocumentRequest
 */
export interface ClusterAddRemoveDocumentRequest {
    /**
     * Name of the draft to add/remove in the cluster
     * @type {string}
     * @memberof ClusterAddRemoveDocumentRequest
     */
    draftName: string;
}

/**
 * Check if a given object implements the ClusterAddRemoveDocumentRequest interface.
 */
export function instanceOfClusterAddRemoveDocumentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "draftName" in value;

    return isInstance;
}

export function ClusterAddRemoveDocumentRequestFromJSON(json: any): ClusterAddRemoveDocumentRequest {
    return ClusterAddRemoveDocumentRequestFromJSONTyped(json, false);
}

export function ClusterAddRemoveDocumentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterAddRemoveDocumentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'draftName': json['draft_name'],
    };
}

export function ClusterAddRemoveDocumentRequestToJSON(value?: ClusterAddRemoveDocumentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'draft_name': value.draftName,
    };
}

