/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClusterMemberRequest
 */
export interface ClusterMemberRequest {
    /**
     * 
     * @type {string}
     * @memberof ClusterMemberRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ClusterMemberRequest
     */
    order: number;
}

/**
 * Check if a given object implements the ClusterMemberRequest interface.
 */
export function instanceOfClusterMemberRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "order" in value;

    return isInstance;
}

export function ClusterMemberRequestFromJSON(json: any): ClusterMemberRequest {
    return ClusterMemberRequestFromJSONTyped(json, false);
}

export function ClusterMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterMemberRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'order': json['order'],
    };
}

export function ClusterMemberRequestToJSON(value?: ClusterMemberRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'order': value.order,
    };
}

