/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a Cluster instance
 * 
 * Uses a nested representation for `documents` rather than the ModelSerializer's
 * handling of relations so we can work with the through model. Specifically, we
 * want to respect the `order_by` setting of the `ClusterMember` class.
 * @export
 * @interface ClusterRequest
 */
export interface ClusterRequest {
    /**
     * 
     * @type {number}
     * @memberof ClusterRequest
     */
    number: number;
    /**
     * List of draft names to add to the cluster
     * @type {Array<string>}
     * @memberof ClusterRequest
     */
    draftNames?: Array<string>;
}

/**
 * Check if a given object implements the ClusterRequest interface.
 */
export function instanceOfClusterRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;

    return isInstance;
}

export function ClusterRequestFromJSON(json: any): ClusterRequest {
    return ClusterRequestFromJSONTyped(json, false);
}

export function ClusterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': json['number'],
        'draftNames': !exists(json, 'draft_names') ? undefined : json['draft_names'],
    };
}

export function ClusterRequestToJSON(value?: ClusterRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'draft_names': value.draftNames,
    };
}

