/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcRelatedDocument } from './RpcRelatedDocument';
import {
    RpcRelatedDocumentFromJSON,
    RpcRelatedDocumentFromJSONTyped,
    RpcRelatedDocumentToJSON,
} from './RpcRelatedDocument';

/**
 * 
 * @export
 * @interface ClusterMember
 */
export interface ClusterMember {
    /**
     * 
     * @type {string}
     * @memberof ClusterMember
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ClusterMember
     */
    readonly rfcNumber?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ClusterMember
     */
    readonly disposition?: string | null;
    /**
     * 
     * @type {Array<RpcRelatedDocument>}
     * @memberof ClusterMember
     */
    readonly references?: Array<RpcRelatedDocument>;
    /**
     * Determine if the document has been received based on related documents
     * @type {boolean}
     * @memberof ClusterMember
     */
    readonly isReceived?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof ClusterMember
     */
    order: number;
}

/**
 * Check if a given object implements the ClusterMember interface.
 */
export function instanceOfClusterMember(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "order" in value;

    return isInstance;
}

export function ClusterMemberFromJSON(json: any): ClusterMember {
    return ClusterMemberFromJSONTyped(json, false);
}

export function ClusterMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterMember {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'rfcNumber': !exists(json, 'rfc_number') ? undefined : json['rfc_number'],
        'disposition': !exists(json, 'disposition') ? undefined : json['disposition'],
        'references': !exists(json, 'references') ? undefined : ((json['references'] as Array<any>).map(RpcRelatedDocumentFromJSON)),
        'isReceived': !exists(json, 'is_received') ? undefined : json['is_received'],
        'order': json['order'],
    };
}

export function ClusterMemberToJSON(value?: ClusterMember | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'order': value.order,
    };
}

