/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ClusterMember } from './ClusterMember';
import {
    ClusterMemberFromJSON,
    ClusterMemberFromJSONTyped,
    ClusterMemberToJSON,
} from './ClusterMember';

/**
 * Serialize a Cluster instance
 * 
 * Uses a nested representation for `documents` rather than the ModelSerializer's
 * handling of relations so we can work with the through model. Specifically, we
 * want to respect the `order_by` setting of the `ClusterMember` class.
 * @export
 * @interface Cluster
 */
export interface Cluster {
    /**
     * 
     * @type {number}
     * @memberof Cluster
     */
    number: number;
    /**
     * 
     * @type {Array<ClusterMember>}
     * @memberof Cluster
     */
    readonly documents?: Array<ClusterMember>;
    /**
     * A cluster is considered active if at least one of its documents is not in
     * terminal state (published/withdrawn).
     * @type {boolean}
     * @memberof Cluster
     */
    readonly isActive?: boolean;
}

/**
 * Check if a given object implements the Cluster interface.
 */
export function instanceOfCluster(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;

    return isInstance;
}

export function ClusterFromJSON(json: any): Cluster {
    return ClusterFromJSONTyped(json, false);
}

export function ClusterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cluster {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': json['number'],
        'documents': !exists(json, 'documents') ? undefined : ((json['documents'] as Array<any>).map(ClusterMemberFromJSON)),
        'isActive': !exists(json, 'is_active') ? undefined : json['is_active'],
    };
}

export function ClusterToJSON(value?: Cluster | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
    };
}

