/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `slate` - slate
 * * `gray` - gray
 * * `zinc` - zinc
 * * `neutral` - neutral
 * * `stone` - stone
 * * `red` - red
 * * `orange` - orange
 * * `amber` - amber
 * * `yellow` - yellow
 * * `lime` - lime
 * * `green` - green
 * * `emerald` - emerald
 * * `teal` - teal
 * * `cyan` - cyan
 * * `sky` - sky
 * * `blue` - blue
 * * `indigo` - indigo
 * * `violet` - violet
 * * `purple` - purple
 * * `fuchsia` - fuchsia
 * * `pink` - pink
 * * `rose` - rose
 * @export
 */
export const ColorEnum = {
    Slate: 'slate',
    Gray: 'gray',
    Zinc: 'zinc',
    Neutral: 'neutral',
    Stone: 'stone',
    Red: 'red',
    Orange: 'orange',
    Amber: 'amber',
    Yellow: 'yellow',
    Lime: 'lime',
    Green: 'green',
    Emerald: 'emerald',
    Teal: 'teal',
    Cyan: 'cyan',
    Sky: 'sky',
    Blue: 'blue',
    Indigo: 'indigo',
    Violet: 'violet',
    Purple: 'purple',
    Fuchsia: 'fuchsia',
    Pink: 'pink',
    Rose: 'rose'
} as const;
export type ColorEnum = typeof ColorEnum[keyof typeof ColorEnum];


export function ColorEnumFromJSON(json: any): ColorEnum {
    return ColorEnumFromJSONTyped(json, false);
}

export function ColorEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorEnum {
    return json as ColorEnum;
}

export function ColorEnumToJSON(value?: ColorEnum | null): any {
    return value as any;
}

