/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for RfcToBe fields that need to be specified explicitly on import
 * @export
 * @interface CreateRfcToBe
 */
export interface CreateRfcToBe {
    /**
     * 
     * @type {string}
     * @memberof CreateRfcToBe
     */
    submittedFormat: string;
    /**
     * TLP IPR boilerplate option applicable when document entered the queue
     * @type {string}
     * @memberof CreateRfcToBe
     */
    submittedBoilerplate: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRfcToBe
     */
    submittedStdLevel: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRfcToBe
     */
    submittedStream: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateRfcToBe
     */
    externalDeadline?: Date | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateRfcToBe
     */
    labels: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof CreateRfcToBe
     */
    draft?: number | null;
}

/**
 * Check if a given object implements the CreateRfcToBe interface.
 */
export function instanceOfCreateRfcToBe(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "submittedFormat" in value;
    isInstance = isInstance && "submittedBoilerplate" in value;
    isInstance = isInstance && "submittedStdLevel" in value;
    isInstance = isInstance && "submittedStream" in value;
    isInstance = isInstance && "labels" in value;

    return isInstance;
}

export function CreateRfcToBeFromJSON(json: any): CreateRfcToBe {
    return CreateRfcToBeFromJSONTyped(json, false);
}

export function CreateRfcToBeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRfcToBe {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'submittedFormat': json['submitted_format'],
        'submittedBoilerplate': json['submitted_boilerplate'],
        'submittedStdLevel': json['submitted_std_level'],
        'submittedStream': json['submitted_stream'],
        'externalDeadline': !exists(json, 'external_deadline') ? undefined : (json['external_deadline'] === null ? null : new Date(json['external_deadline'])),
        'labels': json['labels'],
        'draft': !exists(json, 'draft') ? undefined : json['draft'],
    };
}

export function CreateRfcToBeToJSON(value?: CreateRfcToBe | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'submitted_format': value.submittedFormat,
        'submitted_boilerplate': value.submittedBoilerplate,
        'submitted_std_level': value.submittedStdLevel,
        'submitted_stream': value.submittedStream,
        'external_deadline': value.externalDeadline === undefined ? undefined : (value.externalDeadline === null ? null : value.externalDeadline.toISOString()),
        'labels': value.labels,
        'draft': value.draft,
    };
}

