/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for creating a related document for an RfcToBe
 * @export
 * @interface CreateRpcRelatedDocument
 */
export interface CreateRpcRelatedDocument {
    /**
     * 
     * @type {number}
     * @memberof CreateRpcRelatedDocument
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateRpcRelatedDocument
     */
    relationship: string;
    /**
     * 
     * @type {number}
     * @memberof CreateRpcRelatedDocument
     */
    source: number;
    /**
     * 
     * @type {string}
     * @memberof CreateRpcRelatedDocument
     */
    readonly draftName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRpcRelatedDocument
     */
    targetDraftName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRpcRelatedDocument
     */
    readonly targetDraftNameOutput?: string;
}

/**
 * Check if a given object implements the CreateRpcRelatedDocument interface.
 */
export function instanceOfCreateRpcRelatedDocument(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "relationship" in value;
    isInstance = isInstance && "source" in value;
    isInstance = isInstance && "targetDraftName" in value;

    return isInstance;
}

export function CreateRpcRelatedDocumentFromJSON(json: any): CreateRpcRelatedDocument {
    return CreateRpcRelatedDocumentFromJSONTyped(json, false);
}

export function CreateRpcRelatedDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRpcRelatedDocument {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'relationship': json['relationship'],
        'source': json['source'],
        'draftName': !exists(json, 'draft_name') ? undefined : json['draft_name'],
        'targetDraftName': json['target_draft_name'],
        'targetDraftNameOutput': !exists(json, 'target_draft_name_output') ? undefined : json['target_draft_name_output'],
    };
}

export function CreateRpcRelatedDocumentToJSON(value?: CreateRpcRelatedDocument | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'relationship': value.relationship,
        'source': value.source,
        'target_draft_name': value.targetDraftName,
    };
}

