/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for creating FinalApproval instances
 * @export
 * @interface CreateFinalApprovalRequest
 */
export interface CreateFinalApprovalRequest {
    /**
     * 
     * @type {Date}
     * @memberof CreateFinalApprovalRequest
     */
    approved?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof CreateFinalApprovalRequest
     */
    approverPersonId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateFinalApprovalRequest
     */
    overridingApproverPersonId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateFinalApprovalRequest
     */
    comment?: string;
}

/**
 * Check if a given object implements the CreateFinalApprovalRequest interface.
 */
export function instanceOfCreateFinalApprovalRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "approverPersonId" in value;

    return isInstance;
}

export function CreateFinalApprovalRequestFromJSON(json: any): CreateFinalApprovalRequest {
    return CreateFinalApprovalRequestFromJSONTyped(json, false);
}

export function CreateFinalApprovalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFinalApprovalRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'approved': !exists(json, 'approved') ? undefined : (json['approved'] === null ? null : new Date(json['approved'])),
        'approverPersonId': json['approver_person_id'],
        'overridingApproverPersonId': !exists(json, 'overriding_approver_person_id') ? undefined : json['overriding_approver_person_id'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
    };
}

export function CreateFinalApprovalRequestToJSON(value?: CreateFinalApprovalRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'approved': value.approved === undefined ? undefined : (value.approved === null ? null : value.approved.toISOString()),
        'approver_person_id': value.approverPersonId,
        'overriding_approver_person_id': value.overridingApproverPersonId,
        'comment': value.comment,
    };
}

