/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IanaStatusSlugEnum } from './IanaStatusSlugEnum';
import {
    IanaStatusSlugEnumFromJSON,
    IanaStatusSlugEnumFromJSONTyped,
    IanaStatusSlugEnumToJSON,
} from './IanaStatusSlugEnum';

/**
 * Serializer for RfcToBe fields that need to be specified explicitly on import
 * @export
 * @interface CreateRfcToBeRequest
 */
export interface CreateRfcToBeRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRfcToBeRequest
     */
    submittedFormat: string;
    /**
     * TLP IPR boilerplate option
     * @type {string}
     * @memberof CreateRfcToBeRequest
     */
    boilerplate: string;
    /**
     * Current StdLevel
     * @type {string}
     * @memberof CreateRfcToBeRequest
     */
    stdLevel: string;
    /**
     * Current stream
     * @type {string}
     * @memberof CreateRfcToBeRequest
     */
    stream: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateRfcToBeRequest
     */
    externalDeadline?: Date | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateRfcToBeRequest
     */
    labels: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof CreateRfcToBeRequest
     */
    draft?: number | null;
    /**
     * Document title
     * @type {string}
     * @memberof CreateRfcToBeRequest
     */
    title: string;
    /**
     * Acronym of datatracker group where this document originated, if any
     * @type {string}
     * @memberof CreateRfcToBeRequest
     */
    group?: string;
    /**
     * Document abstract
     * @type {string}
     * @memberof CreateRfcToBeRequest
     */
    _abstract?: string;
    /**
     * Document shepherd
     * @type {number}
     * @memberof CreateRfcToBeRequest
     */
    shepherd?: number | null;
    /**
     * Responsible or shepherding AD, if any
     * @type {number}
     * @memberof CreateRfcToBeRequest
     */
    iesgContact?: number | null;
    /**
     * Page count
     * @type {number}
     * @memberof CreateRfcToBeRequest
     */
    pages?: number | null;
    /**
     * Comma-separated list of keywords
     * @type {string}
     * @memberof CreateRfcToBeRequest
     */
    keywords?: string;
    /**
     * 
     * @type {IanaStatusSlugEnum}
     * @memberof CreateRfcToBeRequest
     */
    ianaStatusSlug?: IanaStatusSlugEnum;
    /**
     * Whether document has consensus (None=unknown)
     * @type {boolean}
     * @memberof CreateRfcToBeRequest
     */
    consensus?: boolean | null;
}

/**
 * Check if a given object implements the CreateRfcToBeRequest interface.
 */
export function instanceOfCreateRfcToBeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "submittedFormat" in value;
    isInstance = isInstance && "boilerplate" in value;
    isInstance = isInstance && "stdLevel" in value;
    isInstance = isInstance && "stream" in value;
    isInstance = isInstance && "labels" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function CreateRfcToBeRequestFromJSON(json: any): CreateRfcToBeRequest {
    return CreateRfcToBeRequestFromJSONTyped(json, false);
}

export function CreateRfcToBeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRfcToBeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'submittedFormat': json['submitted_format'],
        'boilerplate': json['boilerplate'],
        'stdLevel': json['std_level'],
        'stream': json['stream'],
        'externalDeadline': !exists(json, 'external_deadline') ? undefined : (json['external_deadline'] === null ? null : new Date(json['external_deadline'])),
        'labels': json['labels'],
        'draft': !exists(json, 'draft') ? undefined : json['draft'],
        'title': json['title'],
        'group': !exists(json, 'group') ? undefined : json['group'],
        '_abstract': !exists(json, 'abstract') ? undefined : json['abstract'],
        'shepherd': !exists(json, 'shepherd') ? undefined : json['shepherd'],
        'iesgContact': !exists(json, 'iesg_contact') ? undefined : json['iesg_contact'],
        'pages': !exists(json, 'pages') ? undefined : json['pages'],
        'keywords': !exists(json, 'keywords') ? undefined : json['keywords'],
        'ianaStatusSlug': !exists(json, 'iana_status_slug') ? undefined : IanaStatusSlugEnumFromJSON(json['iana_status_slug']),
        'consensus': !exists(json, 'consensus') ? undefined : json['consensus'],
    };
}

export function CreateRfcToBeRequestToJSON(value?: CreateRfcToBeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'submitted_format': value.submittedFormat,
        'boilerplate': value.boilerplate,
        'std_level': value.stdLevel,
        'stream': value.stream,
        'external_deadline': value.externalDeadline === undefined ? undefined : (value.externalDeadline === null ? null : value.externalDeadline.toISOString()),
        'labels': value.labels,
        'draft': value.draft,
        'title': value.title,
        'group': value.group,
        'abstract': value._abstract,
        'shepherd': value.shepherd,
        'iesg_contact': value.iesgContact,
        'pages': value.pages,
        'keywords': value.keywords,
        'iana_status_slug': IanaStatusSlugEnumToJSON(value.ianaStatusSlug),
        'consensus': value.consensus,
    };
}

