/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRfcAuthor
 */
export interface CreateRfcAuthor {
    /**
     * 
     * @type {number}
     * @memberof CreateRfcAuthor
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateRfcAuthor
     */
    readonly name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRfcAuthor
     */
    readonly email?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRfcAuthor
     */
    titlepageName: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateRfcAuthor
     */
    isEditor?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateRfcAuthor
     */
    readonly picture?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRfcAuthor
     */
    readonly datatrackerUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRfcAuthor
     */
    affiliation?: string | null;
}

/**
 * Check if a given object implements the CreateRfcAuthor interface.
 */
export function instanceOfCreateRfcAuthor(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "titlepageName" in value;

    return isInstance;
}

export function CreateRfcAuthorFromJSON(json: any): CreateRfcAuthor {
    return CreateRfcAuthorFromJSONTyped(json, false);
}

export function CreateRfcAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRfcAuthor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'titlepageName': json['titlepage_name'],
        'isEditor': !exists(json, 'is_editor') ? undefined : json['is_editor'],
        'picture': !exists(json, 'picture') ? undefined : json['picture'],
        'datatrackerUrl': !exists(json, 'datatracker_url') ? undefined : json['datatracker_url'],
        'affiliation': !exists(json, 'affiliation') ? undefined : json['affiliation'],
    };
}

export function CreateRfcAuthorToJSON(value?: CreateRfcAuthor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'titlepage_name': value.titlepageName,
        'is_editor': value.isEditor,
        'affiliation': value.affiliation,
    };
}

