/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseDatatrackerPerson } from './BaseDatatrackerPerson';
import {
    BaseDatatrackerPersonFromJSON,
    BaseDatatrackerPersonFromJSONTyped,
    BaseDatatrackerPersonToJSON,
} from './BaseDatatrackerPerson';
import type { MinimalRfcToBe } from './MinimalRfcToBe';
import {
    MinimalRfcToBeFromJSON,
    MinimalRfcToBeFromJSONTyped,
    MinimalRfcToBeToJSON,
} from './MinimalRfcToBe';

/**
 * Serializer for creating FinalApproval instances
 * @export
 * @interface CreateFinalApproval
 */
export interface CreateFinalApproval {
    /**
     * 
     * @type {number}
     * @memberof CreateFinalApproval
     */
    readonly id?: number;
    /**
     * 
     * @type {MinimalRfcToBe}
     * @memberof CreateFinalApproval
     */
    readonly rfcToBe?: MinimalRfcToBe;
    /**
     * 
     * @type {Date}
     * @memberof CreateFinalApproval
     */
    readonly requested?: Date;
    /**
     * 
     * @type {BaseDatatrackerPerson}
     * @memberof CreateFinalApproval
     */
    readonly approver?: BaseDatatrackerPerson;
    /**
     * 
     * @type {Date}
     * @memberof CreateFinalApproval
     */
    approved?: Date | null;
    /**
     * 
     * @type {BaseDatatrackerPerson}
     * @memberof CreateFinalApproval
     */
    readonly overridingApprover?: BaseDatatrackerPerson | null;
    /**
     * 
     * @type {string}
     * @memberof CreateFinalApproval
     */
    comment?: string;
}

/**
 * Check if a given object implements the CreateFinalApproval interface.
 */
export function instanceOfCreateFinalApproval(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateFinalApprovalFromJSON(json: any): CreateFinalApproval {
    return CreateFinalApprovalFromJSONTyped(json, false);
}

export function CreateFinalApprovalFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFinalApproval {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'rfcToBe': !exists(json, 'rfc_to_be') ? undefined : MinimalRfcToBeFromJSON(json['rfc_to_be']),
        'requested': !exists(json, 'requested') ? undefined : (new Date(json['requested'])),
        'approver': !exists(json, 'approver') ? undefined : BaseDatatrackerPersonFromJSON(json['approver']),
        'approved': !exists(json, 'approved') ? undefined : (json['approved'] === null ? null : new Date(json['approved'])),
        'overridingApprover': !exists(json, 'overriding_approver') ? undefined : BaseDatatrackerPersonFromJSON(json['overriding_approver']),
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
    };
}

export function CreateFinalApprovalToJSON(value?: CreateFinalApproval | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'approved': value.approved === undefined ? undefined : (value.approved === null ? null : value.approved.toISOString()),
        'comment': value.comment,
    };
}

