/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRfcAuthorRequest
 */
export interface CreateRfcAuthorRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRfcAuthorRequest
     */
    titlepageName: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateRfcAuthorRequest
     */
    isEditor?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateRfcAuthorRequest
     */
    affiliation?: string | null;
    /**
     * datatracker ID of a Person
     * @type {number}
     * @memberof CreateRfcAuthorRequest
     */
    personId?: number | null;
}

/**
 * Check if a given object implements the CreateRfcAuthorRequest interface.
 */
export function instanceOfCreateRfcAuthorRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "titlepageName" in value;

    return isInstance;
}

export function CreateRfcAuthorRequestFromJSON(json: any): CreateRfcAuthorRequest {
    return CreateRfcAuthorRequestFromJSONTyped(json, false);
}

export function CreateRfcAuthorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRfcAuthorRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'titlepageName': json['titlepage_name'],
        'isEditor': !exists(json, 'is_editor') ? undefined : json['is_editor'],
        'affiliation': !exists(json, 'affiliation') ? undefined : json['affiliation'],
        'personId': !exists(json, 'person_id') ? undefined : json['person_id'],
    };
}

export function CreateRfcAuthorRequestToJSON(value?: CreateRfcAuthorRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'titlepage_name': value.titlepageName,
        'is_editor': value.isEditor,
        'affiliation': value.affiliation,
        'person_id': value.personId,
    };
}

