/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for creating a related document for an RfcToBe
 * @export
 * @interface CreateRpcRelatedDocumentRequest
 */
export interface CreateRpcRelatedDocumentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRpcRelatedDocumentRequest
     */
    relationship: string;
    /**
     * 
     * @type {number}
     * @memberof CreateRpcRelatedDocumentRequest
     */
    source: number;
    /**
     * 
     * @type {string}
     * @memberof CreateRpcRelatedDocumentRequest
     */
    targetDraftName: string;
}

/**
 * Check if a given object implements the CreateRpcRelatedDocumentRequest interface.
 */
export function instanceOfCreateRpcRelatedDocumentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "relationship" in value;
    isInstance = isInstance && "source" in value;
    isInstance = isInstance && "targetDraftName" in value;

    return isInstance;
}

export function CreateRpcRelatedDocumentRequestFromJSON(json: any): CreateRpcRelatedDocumentRequest {
    return CreateRpcRelatedDocumentRequestFromJSONTyped(json, false);
}

export function CreateRpcRelatedDocumentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRpcRelatedDocumentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'relationship': json['relationship'],
        'source': json['source'],
        'targetDraftName': json['target_draft_name'],
    };
}

export function CreateRpcRelatedDocumentRequestToJSON(value?: CreateRpcRelatedDocumentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'relationship': value.relationship,
        'source': value.source,
        'target_draft_name': value.targetDraftName,
    };
}

