/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer a DatatrackerPerson, including all the bells and whistles
 * @export
 * @interface DatatrackerPersonRequest
 */
export interface DatatrackerPersonRequest {
    /**
     * 
     * @type {number}
     * @memberof DatatrackerPersonRequest
     */
    personId: number;
}

/**
 * Check if a given object implements the DatatrackerPersonRequest interface.
 */
export function instanceOfDatatrackerPersonRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "personId" in value;

    return isInstance;
}

export function DatatrackerPersonRequestFromJSON(json: any): DatatrackerPersonRequest {
    return DatatrackerPersonRequestFromJSONTyped(json, false);
}

export function DatatrackerPersonRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatatrackerPersonRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'personId': json['person_id'],
    };
}

export function DatatrackerPersonRequestToJSON(value?: DatatrackerPersonRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'person_id': value.personId,
    };
}

