/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a comment on an RfcToBe
 * @export
 * @interface DocumentCommentRequest
 */
export interface DocumentCommentRequest {
    /**
     * 
     * @type {string}
     * @memberof DocumentCommentRequest
     */
    comment: string;
}

/**
 * Check if a given object implements the DocumentCommentRequest interface.
 */
export function instanceOfDocumentCommentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "comment" in value;

    return isInstance;
}

export function DocumentCommentRequestFromJSON(json: any): DocumentCommentRequest {
    return DocumentCommentRequestFromJSONTyped(json, false);
}

export function DocumentCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentCommentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': json['comment'],
    };
}

export function DocumentCommentRequestToJSON(value?: DocumentCommentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
    };
}

