/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DatatrackerPerson } from './DatatrackerPerson';
import {
    DatatrackerPersonFromJSON,
    DatatrackerPersonFromJSONTyped,
    DatatrackerPersonToJSON,
} from './DatatrackerPerson';
import type { HistoryLastEdit } from './HistoryLastEdit';
import {
    HistoryLastEditFromJSON,
    HistoryLastEditFromJSONTyped,
    HistoryLastEditToJSON,
} from './HistoryLastEdit';

/**
 * Serialize a comment on an RfcToBe
 * @export
 * @interface DocumentComment
 */
export interface DocumentComment {
    /**
     * 
     * @type {number}
     * @memberof DocumentComment
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentComment
     */
    comment: string;
    /**
     * 
     * @type {DatatrackerPerson}
     * @memberof DocumentComment
     */
    readonly by?: DatatrackerPerson;
    /**
     * 
     * @type {Date}
     * @memberof DocumentComment
     */
    readonly time?: Date;
    /**
     * 
     * @type {HistoryLastEdit}
     * @memberof DocumentComment
     */
    readonly lastEdit?: HistoryLastEdit;
}

/**
 * Check if a given object implements the DocumentComment interface.
 */
export function instanceOfDocumentComment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "comment" in value;

    return isInstance;
}

export function DocumentCommentFromJSON(json: any): DocumentComment {
    return DocumentCommentFromJSONTyped(json, false);
}

export function DocumentCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentComment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'comment': json['comment'],
        'by': !exists(json, 'by') ? undefined : DatatrackerPersonFromJSON(json['by']),
        'time': !exists(json, 'time') ? undefined : (new Date(json['time'])),
        'lastEdit': !exists(json, 'last_edit') ? undefined : HistoryLastEditFromJSON(json['last_edit']),
    };
}

export function DocumentCommentToJSON(value?: DocumentComment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
    };
}

