/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Draft
 */
export interface Draft {
    /**
     * Name of draft
     * @type {string}
     * @memberof Draft
     */
    readonly name?: string;
    /**
     * Revision of draft
     * @type {string}
     * @memberof Draft
     */
    readonly rev?: string;
    /**
     * Title of draft
     * @type {string}
     * @memberof Draft
     */
    readonly title?: string;
    /**
     * Number of pages
     * @type {number}
     * @memberof Draft
     */
    readonly pages?: number;
}

/**
 * Check if a given object implements the Draft interface.
 */
export function instanceOfDraft(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DraftFromJSON(json: any): Draft {
    return DraftFromJSONTyped(json, false);
}

export function DraftFromJSONTyped(json: any, ignoreDiscriminator: boolean): Draft {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'rev': !exists(json, 'rev') ? undefined : json['rev'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'pages': !exists(json, 'pages') ? undefined : json['pages'],
    };
}

export function DraftToJSON(value?: Draft | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

