/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for Errata model
 * @export
 * @interface Errata
 */
export interface Errata {
    /**
     * 
     * @type {number}
     * @memberof Errata
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof Errata
     */
    readonly rfcToBe?: number;
    /**
     * 
     * @type {string}
     * @memberof Errata
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof Errata
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Errata
     */
    section?: string;
    /**
     * 
     * @type {string}
     * @memberof Errata
     */
    origText?: string;
    /**
     * 
     * @type {string}
     * @memberof Errata
     */
    correctedText?: string;
    /**
     * 
     * @type {string}
     * @memberof Errata
     */
    submitterName?: string;
    /**
     * 
     * @type {string}
     * @memberof Errata
     */
    submitterEmail?: string;
    /**
     * 
     * @type {number}
     * @memberof Errata
     */
    submitterDtPerson?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof Errata
     */
    readonly submittedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Errata
     */
    verifiedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Errata
     */
    verifierDtPerson?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof Errata
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Errata
     */
    readonly updatedAt?: Date;
}

/**
 * Check if a given object implements the Errata interface.
 */
export function instanceOfErrata(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ErrataFromJSON(json: any): Errata {
    return ErrataFromJSONTyped(json, false);
}

export function ErrataFromJSONTyped(json: any, ignoreDiscriminator: boolean): Errata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'rfcToBe': !exists(json, 'rfc_to_be') ? undefined : json['rfc_to_be'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'section': !exists(json, 'section') ? undefined : json['section'],
        'origText': !exists(json, 'orig_text') ? undefined : json['orig_text'],
        'correctedText': !exists(json, 'corrected_text') ? undefined : json['corrected_text'],
        'submitterName': !exists(json, 'submitter_name') ? undefined : json['submitter_name'],
        'submitterEmail': !exists(json, 'submitter_email') ? undefined : json['submitter_email'],
        'submitterDtPerson': !exists(json, 'submitter_dt_person') ? undefined : json['submitter_dt_person'],
        'submittedAt': !exists(json, 'submitted_at') ? undefined : (new Date(json['submitted_at'])),
        'verifiedAt': !exists(json, 'verified_at') ? undefined : (json['verified_at'] === null ? null : new Date(json['verified_at'])),
        'verifierDtPerson': !exists(json, 'verifier_dt_person') ? undefined : json['verifier_dt_person'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function ErrataToJSON(value?: Errata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'type': value.type,
        'section': value.section,
        'orig_text': value.origText,
        'corrected_text': value.correctedText,
        'submitter_name': value.submitterName,
        'submitter_email': value.submitterEmail,
        'submitter_dt_person': value.submitterDtPerson,
        'verified_at': value.verifiedAt === undefined ? undefined : (value.verifiedAt === null ? null : value.verifiedAt.toISOString().substring(0,10)),
        'verifier_dt_person': value.verifierDtPerson,
    };
}

