/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DatatrackerPerson } from './DatatrackerPerson';
import {
    DatatrackerPersonFromJSON,
    DatatrackerPersonFromJSONTyped,
    DatatrackerPersonToJSON,
} from './DatatrackerPerson';

/**
 * Serialize the most recent change in a HistoricalRecord
 * @export
 * @interface HistoryLastEdit
 */
export interface HistoryLastEdit {
    /**
     * 
     * @type {DatatrackerPerson}
     * @memberof HistoryLastEdit
     */
    readonly by?: DatatrackerPerson;
    /**
     * 
     * @type {Date}
     * @memberof HistoryLastEdit
     */
    readonly time?: Date;
}

/**
 * Check if a given object implements the HistoryLastEdit interface.
 */
export function instanceOfHistoryLastEdit(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryLastEditFromJSON(json: any): HistoryLastEdit {
    return HistoryLastEditFromJSONTyped(json, false);
}

export function HistoryLastEditFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryLastEdit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'by': !exists(json, 'by') ? undefined : DatatrackerPersonFromJSON(json['by']),
        'time': !exists(json, 'time') ? undefined : (new Date(json['time'])),
    };
}

export function HistoryLastEditToJSON(value?: HistoryLastEdit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

