/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize IANA status with slug and display text
 * @export
 * @interface IanaStatusRequest
 */
export interface IanaStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof IanaStatusRequest
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof IanaStatusRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IanaStatusRequest
     */
    desc: string;
    /**
     * 
     * @type {boolean}
     * @memberof IanaStatusRequest
     */
    used?: boolean;
}

/**
 * Check if a given object implements the IanaStatusRequest interface.
 */
export function instanceOfIanaStatusRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "desc" in value;

    return isInstance;
}

export function IanaStatusRequestFromJSON(json: any): IanaStatusRequest {
    return IanaStatusRequestFromJSONTyped(json, false);
}

export function IanaStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IanaStatusRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'name': json['name'],
        'desc': json['desc'],
        'used': !exists(json, 'used') ? undefined : json['used'],
    };
}

export function IanaStatusRequestToJSON(value?: IanaStatusRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
        'desc': value.desc,
        'used': value.used,
    };
}

