/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `no_actions` - This document has no IANA actions
 * * `not_completed` - IANA has not completed actions in draft
 * * `completed` - IANA has completed actions in draft
 * * `changes_required` - Changes to registries are required due to RFC edits
 * * `reconciled` - IANA has reconciled changes between draft and RFC
 * @export
 */
export const IanaStatusSlugEnum = {
    NoActions: 'no_actions',
    NotCompleted: 'not_completed',
    Completed: 'completed',
    ChangesRequired: 'changes_required',
    Reconciled: 'reconciled'
} as const;
export type IanaStatusSlugEnum = typeof IanaStatusSlugEnum[keyof typeof IanaStatusSlugEnum];


export function IanaStatusSlugEnumFromJSON(json: any): IanaStatusSlugEnum {
    return IanaStatusSlugEnumFromJSONTyped(json, false);
}

export function IanaStatusSlugEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): IanaStatusSlugEnum {
    return json as IanaStatusSlugEnum;
}

export function IanaStatusSlugEnumToJSON(value?: IanaStatusSlugEnum | null): any {
    return value as any;
}

