/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LabelStat } from './LabelStat';
import {
    LabelStatFromJSON,
    LabelStatFromJSONTyped,
    LabelStatToJSON,
} from './LabelStat';

/**
 * 
 * @export
 * @interface LabelStats
 */
export interface LabelStats {
    /**
     * 
     * @type {Array<LabelStat>}
     * @memberof LabelStats
     */
    labelStats: Array<LabelStat>;
}

/**
 * Check if a given object implements the LabelStats interface.
 */
export function instanceOfLabelStats(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "labelStats" in value;

    return isInstance;
}

export function LabelStatsFromJSON(json: any): LabelStats {
    return LabelStatsFromJSONTyped(json, false);
}

export function LabelStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'labelStats': ((json['label_stats'] as Array<any>).map(LabelStatFromJSON)),
    };
}

export function LabelStatsToJSON(value?: LabelStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label_stats': ((value.labelStats as Array<any>).map(LabelStatToJSON)),
    };
}

