/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ColorEnum } from './ColorEnum';
import {
    ColorEnumFromJSON,
    ColorEnumFromJSONTyped,
    ColorEnumToJSON,
} from './ColorEnum';

/**
 * 
 * @export
 * @interface LabelRequest
 */
export interface LabelRequest {
    /**
     * 
     * @type {string}
     * @memberof LabelRequest
     */
    slug: string;
    /**
     * 
     * @type {boolean}
     * @memberof LabelRequest
     */
    isException?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LabelRequest
     */
    isComplexity?: boolean;
    /**
     * 
     * @type {ColorEnum}
     * @memberof LabelRequest
     */
    color?: ColorEnum;
    /**
     * 
     * @type {boolean}
     * @memberof LabelRequest
     */
    used?: boolean;
}

/**
 * Check if a given object implements the LabelRequest interface.
 */
export function instanceOfLabelRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "slug" in value;

    return isInstance;
}

export function LabelRequestFromJSON(json: any): LabelRequest {
    return LabelRequestFromJSONTyped(json, false);
}

export function LabelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'isException': !exists(json, 'is_exception') ? undefined : json['is_exception'],
        'isComplexity': !exists(json, 'is_complexity') ? undefined : json['is_complexity'],
        'color': !exists(json, 'color') ? undefined : ColorEnumFromJSON(json['color']),
        'used': !exists(json, 'used') ? undefined : json['used'],
    };
}

export function LabelRequestToJSON(value?: LabelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'is_exception': value.isException,
        'is_complexity': value.isComplexity,
        'color': ColorEnumToJSON(value.color),
        'used': value.used,
    };
}

