/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabelStat
 */
export interface LabelStat {
    /**
     * 
     * @type {number}
     * @memberof LabelStat
     */
    documentId: number;
    /**
     * 
     * @type {number}
     * @memberof LabelStat
     */
    labelId: number;
    /**
     * 
     * @type {number}
     * @memberof LabelStat
     */
    seconds: number;
}

/**
 * Check if a given object implements the LabelStat interface.
 */
export function instanceOfLabelStat(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "documentId" in value;
    isInstance = isInstance && "labelId" in value;
    isInstance = isInstance && "seconds" in value;

    return isInstance;
}

export function LabelStatFromJSON(json: any): LabelStat {
    return LabelStatFromJSONTyped(json, false);
}

export function LabelStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelStat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documentId': json['document_id'],
        'labelId': json['label_id'],
        'seconds': json['seconds'],
    };
}

export function LabelStatToJSON(value?: LabelStat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'document_id': value.documentId,
        'label_id': value.labelId,
        'seconds': value.seconds,
    };
}

