/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MsgtypeEnum } from './MsgtypeEnum';
import {
    MsgtypeEnumFromJSON,
    MsgtypeEnumFromJSONTyped,
    MsgtypeEnumToJSON,
} from './MsgtypeEnum';

/**
 * Mail message serializer
 * @export
 * @interface MailMessageRequest
 */
export interface MailMessageRequest {
    /**
     * 
     * @type {MsgtypeEnum}
     * @memberof MailMessageRequest
     */
    msgtype: MsgtypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MailMessageRequest
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof MailMessageRequest
     */
    cc?: string;
    /**
     * 
     * @type {string}
     * @memberof MailMessageRequest
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof MailMessageRequest
     */
    body: string;
}

/**
 * Check if a given object implements the MailMessageRequest interface.
 */
export function instanceOfMailMessageRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "msgtype" in value;
    isInstance = isInstance && "to" in value;
    isInstance = isInstance && "subject" in value;
    isInstance = isInstance && "body" in value;

    return isInstance;
}

export function MailMessageRequestFromJSON(json: any): MailMessageRequest {
    return MailMessageRequestFromJSONTyped(json, false);
}

export function MailMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailMessageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'msgtype': MsgtypeEnumFromJSON(json['msgtype']),
        'to': json['to'],
        'cc': !exists(json, 'cc') ? undefined : json['cc'],
        'subject': json['subject'],
        'body': json['body'],
    };
}

export function MailMessageRequestToJSON(value?: MailMessageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'msgtype': MsgtypeEnumToJSON(value.msgtype),
        'to': value.to,
        'cc': value.cc,
        'subject': value.subject,
        'body': value.body,
    };
}

