/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MailAttachmentRequest
 */
export interface MailAttachmentRequest {
    /**
     * 
     * @type {string}
     * @memberof MailAttachmentRequest
     */
    name: string;
    /**
     * 
     * @type {Blob}
     * @memberof MailAttachmentRequest
     */
    content: Blob;
}

/**
 * Check if a given object implements the MailAttachmentRequest interface.
 */
export function instanceOfMailAttachmentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function MailAttachmentRequestFromJSON(json: any): MailAttachmentRequest {
    return MailAttachmentRequestFromJSONTyped(json, false);
}

export function MailAttachmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailAttachmentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'content': json['content'],
    };
}

export function MailAttachmentRequestToJSON(value?: MailAttachmentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'content': value.content,
    };
}

