/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MailAttachment
 */
export interface MailAttachment {
    /**
     * 
     * @type {string}
     * @memberof MailAttachment
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MailAttachment
     */
    content: string;
}

/**
 * Check if a given object implements the MailAttachment interface.
 */
export function instanceOfMailAttachment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function MailAttachmentFromJSON(json: any): MailAttachment {
    return MailAttachmentFromJSONTyped(json, false);
}

export function MailAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailAttachment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'content': json['content'],
    };
}

export function MailAttachmentToJSON(value?: MailAttachment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'content': value.content,
    };
}

