/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MailMessage } from './MailMessage';
import {
    MailMessageFromJSON,
    MailMessageFromJSONTyped,
    MailMessageToJSON,
} from './MailMessage';

/**
 * 
 * @export
 * @interface MailTemplate
 */
export interface MailTemplate {
    /**
     * human readable text for UI
     * @type {string}
     * @memberof MailTemplate
     */
    label: string;
    /**
     * 
     * @type {MailMessage}
     * @memberof MailTemplate
     */
    template: MailMessage;
}

/**
 * Check if a given object implements the MailTemplate interface.
 */
export function instanceOfMailTemplate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "template" in value;

    return isInstance;
}

export function MailTemplateFromJSON(json: any): MailTemplate {
    return MailTemplateFromJSONTyped(json, false);
}

export function MailTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailTemplate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': json['label'],
        'template': MailMessageFromJSON(json['template']),
    };
}

export function MailTemplateToJSON(value?: MailTemplate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'template': MailMessageToJSON(value.template),
    };
}

