/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TypeEnum } from './TypeEnum';
import {
    TypeEnumFromJSON,
    TypeEnumFromJSONTyped,
    TypeEnumToJSON,
} from './TypeEnum';

/**
 * 
 * @export
 * @interface MailResponse
 */
export interface MailResponse {
    /**
     * 
     * @type {TypeEnum}
     * @memberof MailResponse
     */
    type: TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MailResponse
     */
    message: string;
}

/**
 * Check if a given object implements the MailResponse interface.
 */
export function instanceOfMailResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function MailResponseFromJSON(json: any): MailResponse {
    return MailResponseFromJSONTyped(json, false);
}

export function MailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': TypeEnumFromJSON(json['type']),
        'message': json['message'],
    };
}

export function MailResponseToJSON(value?: MailResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': TypeEnumToJSON(value.type),
        'message': value.message,
    };
}

