/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MetadataTableRow } from './MetadataTableRow';
import {
    MetadataTableRowFromJSON,
    MetadataTableRowFromJSONTyped,
    MetadataTableRowToJSON,
} from './MetadataTableRow';

/**
 * 
 * @export
 * @interface MetadataValidationResults
 */
export interface MetadataValidationResults {
    /**
     * 
     * @type {number}
     * @memberof MetadataValidationResults
     */
    rfcToBe: number;
    /**
     * 
     * @type {string}
     * @memberof MetadataValidationResults
     */
    readonly repository?: string;
    /**
     * Head SHA of the commit that was validated
     * @type {string}
     * @memberof MetadataValidationResults
     */
    headSha?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MetadataValidationResults
     */
    readonly canAutofix?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MetadataValidationResults
     */
    readonly isMatch?: boolean;
    /**
     * 
     * @type {Array<MetadataTableRow>}
     * @memberof MetadataValidationResults
     */
    readonly metadataCompare?: Array<MetadataTableRow>;
    /**
     * 
     * @type {string}
     * @memberof MetadataValidationResults
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof MetadataValidationResults
     */
    detail: string;
    /**
     * 
     * @type {boolean}
     * @memberof MetadataValidationResults
     */
    readonly isError?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof MetadataValidationResults
     */
    readonly receivedAt?: Date;
}

/**
 * Check if a given object implements the MetadataValidationResults interface.
 */
export function instanceOfMetadataValidationResults(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rfcToBe" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "detail" in value;

    return isInstance;
}

export function MetadataValidationResultsFromJSON(json: any): MetadataValidationResults {
    return MetadataValidationResultsFromJSONTyped(json, false);
}

export function MetadataValidationResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataValidationResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rfcToBe': json['rfc_to_be'],
        'repository': !exists(json, 'repository') ? undefined : json['repository'],
        'headSha': !exists(json, 'head_sha') ? undefined : json['head_sha'],
        'canAutofix': !exists(json, 'can_autofix') ? undefined : json['can_autofix'],
        'isMatch': !exists(json, 'is_match') ? undefined : json['is_match'],
        'metadataCompare': !exists(json, 'metadata_compare') ? undefined : ((json['metadata_compare'] as Array<any>).map(MetadataTableRowFromJSON)),
        'status': json['status'],
        'detail': json['detail'],
        'isError': !exists(json, 'is_error') ? undefined : json['is_error'],
        'receivedAt': !exists(json, 'received_at') ? undefined : (new Date(json['received_at'])),
    };
}

export function MetadataValidationResultsToJSON(value?: MetadataValidationResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rfc_to_be': value.rfcToBe,
        'head_sha': value.headSha,
        'status': value.status,
        'detail': value.detail,
    };
}

