/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetadataTableRowValue
 */
export interface MetadataTableRowValue {
    /**
     * Value for left column
     * @type {string}
     * @memberof MetadataTableRowValue
     */
    leftValue: string;
    /**
     * Value for right column
     * @type {string}
     * @memberof MetadataTableRowValue
     */
    rightValue: string;
    /**
     * Are the values equivalent?
     * @type {boolean}
     * @memberof MetadataTableRowValue
     */
    isMatch: boolean;
    /**
     * Can the difference be auto-fixed?
     * @type {boolean}
     * @memberof MetadataTableRowValue
     */
    canAutoFix: boolean;
    /**
     * Is the difference an error?
     * @type {boolean}
     * @memberof MetadataTableRowValue
     */
    isError: boolean;
    /**
     * Additional details about the difference
     * @type {string}
     * @memberof MetadataTableRowValue
     */
    detail: string;
}

/**
 * Check if a given object implements the MetadataTableRowValue interface.
 */
export function instanceOfMetadataTableRowValue(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "leftValue" in value;
    isInstance = isInstance && "rightValue" in value;
    isInstance = isInstance && "isMatch" in value;
    isInstance = isInstance && "canAutoFix" in value;
    isInstance = isInstance && "isError" in value;
    isInstance = isInstance && "detail" in value;

    return isInstance;
}

export function MetadataTableRowValueFromJSON(json: any): MetadataTableRowValue {
    return MetadataTableRowValueFromJSONTyped(json, false);
}

export function MetadataTableRowValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataTableRowValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'leftValue': json['left_value'],
        'rightValue': json['right_value'],
        'isMatch': json['is_match'],
        'canAutoFix': json['can_auto_fix'],
        'isError': json['is_error'],
        'detail': json['detail'],
    };
}

export function MetadataTableRowValueToJSON(value?: MetadataTableRowValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'left_value': value.leftValue,
        'right_value': value.rightValue,
        'is_match': value.isMatch,
        'can_auto_fix': value.canAutoFix,
        'is_error': value.isError,
        'detail': value.detail,
    };
}

