/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MetadataTableRowValue } from './MetadataTableRowValue';
import {
    MetadataTableRowValueFromJSON,
    MetadataTableRowValueFromJSONTyped,
    MetadataTableRowValueToJSON,
} from './MetadataTableRowValue';

/**
 * 
 * @export
 * @interface MetadataTableRow
 */
export interface MetadataTableRow {
    /**
     * 
     * @type {string}
     * @memberof MetadataTableRow
     */
    rowName: string;
    /**
     * 
     * @type {number}
     * @memberof MetadataTableRow
     */
    rowNameListDepth: number;
    /**
     * 
     * @type {MetadataTableRowValue}
     * @memberof MetadataTableRow
     */
    rowValue: MetadataTableRowValue;
}

/**
 * Check if a given object implements the MetadataTableRow interface.
 */
export function instanceOfMetadataTableRow(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rowName" in value;
    isInstance = isInstance && "rowNameListDepth" in value;
    isInstance = isInstance && "rowValue" in value;

    return isInstance;
}

export function MetadataTableRowFromJSON(json: any): MetadataTableRow {
    return MetadataTableRowFromJSONTyped(json, false);
}

export function MetadataTableRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataTableRow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rowName': json['row_name'],
        'rowNameListDepth': json['row_name_list_depth'],
        'rowValue': MetadataTableRowValueFromJSON(json['row_value']),
    };
}

export function MetadataTableRowToJSON(value?: MetadataTableRow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'row_name': value.rowName,
        'row_name_list_depth': value.rowNameListDepth,
        'row_value': MetadataTableRowValueToJSON(value.rowValue),
    };
}

