/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MinimalRfcToBeRequest
 */
export interface MinimalRfcToBeRequest {
    /**
     * 
     * @type {number}
     * @memberof MinimalRfcToBeRequest
     */
    rfcNumber?: number | null;
}

/**
 * Check if a given object implements the MinimalRfcToBeRequest interface.
 */
export function instanceOfMinimalRfcToBeRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MinimalRfcToBeRequestFromJSON(json: any): MinimalRfcToBeRequest {
    return MinimalRfcToBeRequestFromJSONTyped(json, false);
}

export function MinimalRfcToBeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinimalRfcToBeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rfcNumber': !exists(json, 'rfc_number') ? undefined : json['rfc_number'],
    };
}

export function MinimalRfcToBeRequestToJSON(value?: MinimalRfcToBeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rfc_number': value.rfcNumber,
    };
}

