/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MinimalRfcToBe
 */
export interface MinimalRfcToBe {
    /**
     * 
     * @type {string}
     * @memberof MinimalRfcToBe
     */
    readonly name?: string;
    /**
     * 
     * @type {number}
     * @memberof MinimalRfcToBe
     */
    rfcNumber?: number | null;
}

/**
 * Check if a given object implements the MinimalRfcToBe interface.
 */
export function instanceOfMinimalRfcToBe(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MinimalRfcToBeFromJSON(json: any): MinimalRfcToBe {
    return MinimalRfcToBeFromJSONTyped(json, false);
}

export function MinimalRfcToBeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinimalRfcToBe {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'rfcNumber': !exists(json, 'rfc_number') ? undefined : json['rfc_number'],
    };
}

export function MinimalRfcToBeToJSON(value?: MinimalRfcToBe | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rfc_number': value.rfcNumber,
    };
}

