/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `blank` - freeform
 * * `finalapproval` - final approval
 * * `publication` - publication announcement
 * @export
 */
export const MsgtypeEnum = {
    Blank: 'blank',
    Finalapproval: 'finalapproval',
    Publication: 'publication'
} as const;
export type MsgtypeEnum = typeof MsgtypeEnum[keyof typeof MsgtypeEnum];


export function MsgtypeEnumFromJSON(json: any): MsgtypeEnum {
    return MsgtypeEnumFromJSONTyped(json, false);
}

export function MsgtypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MsgtypeEnum {
    return json as MsgtypeEnum;
}

export function MsgtypeEnumToJSON(value?: MsgtypeEnum | null): any {
    return value as any;
}

