/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RfcToBe } from './RfcToBe';
import {
    RfcToBeFromJSON,
    RfcToBeFromJSONTyped,
    RfcToBeToJSON,
} from './RfcToBe';
import type { StateEnum } from './StateEnum';
import {
    StateEnumFromJSON,
    StateEnumFromJSONTyped,
    StateEnumToJSON,
} from './StateEnum';

/**
 * Assignment serializer with nested RfcToBe details
 * @export
 * @interface NestedAssignment
 */
export interface NestedAssignment {
    /**
     * 
     * @type {number}
     * @memberof NestedAssignment
     */
    readonly id?: number;
    /**
     * 
     * @type {RfcToBe}
     * @memberof NestedAssignment
     */
    readonly rfcToBe?: RfcToBe;
    /**
     * 
     * @type {number}
     * @memberof NestedAssignment
     */
    person?: number | null;
    /**
     * 
     * @type {string}
     * @memberof NestedAssignment
     */
    role: string;
    /**
     * 
     * @type {StateEnum}
     * @memberof NestedAssignment
     */
    state?: StateEnum;
    /**
     * 
     * @type {string}
     * @memberof NestedAssignment
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof NestedAssignment
     */
    timeSpent?: string;
}

/**
 * Check if a given object implements the NestedAssignment interface.
 */
export function instanceOfNestedAssignment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function NestedAssignmentFromJSON(json: any): NestedAssignment {
    return NestedAssignmentFromJSONTyped(json, false);
}

export function NestedAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): NestedAssignment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'rfcToBe': !exists(json, 'rfc_to_be') ? undefined : RfcToBeFromJSON(json['rfc_to_be']),
        'person': !exists(json, 'person') ? undefined : json['person'],
        'role': json['role'],
        'state': !exists(json, 'state') ? undefined : StateEnumFromJSON(json['state']),
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'timeSpent': !exists(json, 'time_spent') ? undefined : json['time_spent'],
    };
}

export function NestedAssignmentToJSON(value?: NestedAssignment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'person': value.person,
        'role': value.role,
        'state': StateEnumToJSON(value.state),
        'comment': value.comment,
        'time_spent': value.timeSpent,
    };
}

