/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Erratum } from './Erratum';
import {
    ErratumFromJSON,
    ErratumFromJSONTyped,
    ErratumToJSON,
} from './Erratum';

/**
 * 
 * @export
 * @interface PaginatedErratumList
 */
export interface PaginatedErratumList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedErratumList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedErratumList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedErratumList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Erratum>}
     * @memberof PaginatedErratumList
     */
    results: Array<Erratum>;
}

/**
 * Check if a given object implements the PaginatedErratumList interface.
 */
export function instanceOfPaginatedErratumList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function PaginatedErratumListFromJSON(json: any): PaginatedErratumList {
    return PaginatedErratumListFromJSONTyped(json, false);
}

export function PaginatedErratumListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedErratumList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ErratumFromJSON)),
    };
}

export function PaginatedErratumListToJSON(value?: PaginatedErratumList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(ErratumToJSON)),
    };
}

