/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Errata } from './Errata';
import {
    ErrataFromJSON,
    ErrataFromJSONTyped,
    ErrataToJSON,
} from './Errata';

/**
 * 
 * @export
 * @interface PaginatedErrataList
 */
export interface PaginatedErrataList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedErrataList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedErrataList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedErrataList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Errata>}
     * @memberof PaginatedErrataList
     */
    results: Array<Errata>;
}

/**
 * Check if a given object implements the PaginatedErrataList interface.
 */
export function instanceOfPaginatedErrataList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function PaginatedErrataListFromJSON(json: any): PaginatedErrataList {
    return PaginatedErrataListFromJSONTyped(json, false);
}

export function PaginatedErrataListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedErrataList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ErrataFromJSON)),
    };
}

export function PaginatedErrataListToJSON(value?: PaginatedErrataList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(ErrataToJSON)),
    };
}

