/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RfcToBe } from './RfcToBe';
import {
    RfcToBeFromJSON,
    RfcToBeFromJSONTyped,
    RfcToBeToJSON,
} from './RfcToBe';

/**
 * 
 * @export
 * @interface PaginatedRfcToBeList
 */
export interface PaginatedRfcToBeList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRfcToBeList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRfcToBeList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRfcToBeList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RfcToBe>}
     * @memberof PaginatedRfcToBeList
     */
    results: Array<RfcToBe>;
}

/**
 * Check if a given object implements the PaginatedRfcToBeList interface.
 */
export function instanceOfPaginatedRfcToBeList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function PaginatedRfcToBeListFromJSON(json: any): PaginatedRfcToBeList {
    return PaginatedRfcToBeListFromJSONTyped(json, false);
}

export function PaginatedRfcToBeListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRfcToBeList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(RfcToBeFromJSON)),
    };
}

export function PaginatedRfcToBeListToJSON(value?: PaginatedRfcToBeList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(RfcToBeToJSON)),
    };
}

