/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentComment } from './DocumentComment';
import {
    DocumentCommentFromJSON,
    DocumentCommentFromJSONTyped,
    DocumentCommentToJSON,
} from './DocumentComment';

/**
 * 
 * @export
 * @interface PaginatedDocumentCommentList
 */
export interface PaginatedDocumentCommentList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedDocumentCommentList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDocumentCommentList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedDocumentCommentList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<DocumentComment>}
     * @memberof PaginatedDocumentCommentList
     */
    results: Array<DocumentComment>;
}

/**
 * Check if a given object implements the PaginatedDocumentCommentList interface.
 */
export function instanceOfPaginatedDocumentCommentList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function PaginatedDocumentCommentListFromJSON(json: any): PaginatedDocumentCommentList {
    return PaginatedDocumentCommentListFromJSONTyped(json, false);
}

export function PaginatedDocumentCommentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedDocumentCommentList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(DocumentCommentFromJSON)),
    };
}

export function PaginatedDocumentCommentListToJSON(value?: PaginatedDocumentCommentList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(DocumentCommentToJSON)),
    };
}

