/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseDatatrackerPerson } from './BaseDatatrackerPerson';
import {
    BaseDatatrackerPersonFromJSON,
    BaseDatatrackerPersonFromJSONTyped,
    BaseDatatrackerPersonToJSON,
} from './BaseDatatrackerPerson';

/**
 * 
 * @export
 * @interface PaginatedBaseDatatrackerPersonList
 */
export interface PaginatedBaseDatatrackerPersonList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedBaseDatatrackerPersonList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBaseDatatrackerPersonList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBaseDatatrackerPersonList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<BaseDatatrackerPerson>}
     * @memberof PaginatedBaseDatatrackerPersonList
     */
    results: Array<BaseDatatrackerPerson>;
}

/**
 * Check if a given object implements the PaginatedBaseDatatrackerPersonList interface.
 */
export function instanceOfPaginatedBaseDatatrackerPersonList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function PaginatedBaseDatatrackerPersonListFromJSON(json: any): PaginatedBaseDatatrackerPersonList {
    return PaginatedBaseDatatrackerPersonListFromJSONTyped(json, false);
}

export function PaginatedBaseDatatrackerPersonListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBaseDatatrackerPersonList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(BaseDatatrackerPersonFromJSON)),
    };
}

export function PaginatedBaseDatatrackerPersonListToJSON(value?: PaginatedBaseDatatrackerPersonList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(BaseDatatrackerPersonToJSON)),
    };
}

