/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a SubseriesMember
 * @export
 * @interface PatchedSubseriesMemberRequest
 */
export interface PatchedSubseriesMemberRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedSubseriesMemberRequest
     */
    rfcToBe?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedSubseriesMemberRequest
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedSubseriesMemberRequest
     */
    number?: number;
}

/**
 * Check if a given object implements the PatchedSubseriesMemberRequest interface.
 */
export function instanceOfPatchedSubseriesMemberRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedSubseriesMemberRequestFromJSON(json: any): PatchedSubseriesMemberRequest {
    return PatchedSubseriesMemberRequestFromJSONTyped(json, false);
}

export function PatchedSubseriesMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSubseriesMemberRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rfcToBe': !exists(json, 'rfc_to_be') ? undefined : json['rfc_to_be'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'number': !exists(json, 'number') ? undefined : json['number'],
    };
}

export function PatchedSubseriesMemberRequestToJSON(value?: PatchedSubseriesMemberRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rfc_to_be': value.rfcToBe,
        'type': value.type,
        'number': value.number,
    };
}

