/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedRfcAuthor
 */
export interface PatchedRfcAuthor {
    /**
     * 
     * @type {number}
     * @memberof PatchedRfcAuthor
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcAuthor
     */
    readonly name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcAuthor
     */
    readonly email?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcAuthor
     */
    titlepageName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedRfcAuthor
     */
    isEditor?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcAuthor
     */
    readonly picture?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcAuthor
     */
    readonly datatrackerUrl?: string;
}

/**
 * Check if a given object implements the PatchedRfcAuthor interface.
 */
export function instanceOfPatchedRfcAuthor(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedRfcAuthorFromJSON(json: any): PatchedRfcAuthor {
    return PatchedRfcAuthorFromJSONTyped(json, false);
}

export function PatchedRfcAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRfcAuthor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'titlepageName': !exists(json, 'titlepage_name') ? undefined : json['titlepage_name'],
        'isEditor': !exists(json, 'is_editor') ? undefined : json['is_editor'],
        'picture': !exists(json, 'picture') ? undefined : json['picture'],
        'datatrackerUrl': !exists(json, 'datatracker_url') ? undefined : json['datatracker_url'],
    };
}

export function PatchedRfcAuthorToJSON(value?: PatchedRfcAuthor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'titlepage_name': value.titlepageName,
        'is_editor': value.isEditor,
    };
}

