/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a Cluster instance
 * 
 * Uses a nested representation for `documents` rather than the ModelSerializer's
 * handling of relations so we can work with the through model. Specifically, we
 * want to respect the `order_by` setting of the `ClusterMember` class.
 * @export
 * @interface PatchedClusterRequest
 */
export interface PatchedClusterRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedClusterRequest
     */
    number?: number;
    /**
     * List of draft names to add to the cluster
     * @type {Array<string>}
     * @memberof PatchedClusterRequest
     */
    draftNames?: Array<string>;
}

/**
 * Check if a given object implements the PatchedClusterRequest interface.
 */
export function instanceOfPatchedClusterRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedClusterRequestFromJSON(json: any): PatchedClusterRequest {
    return PatchedClusterRequestFromJSONTyped(json, false);
}

export function PatchedClusterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedClusterRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': !exists(json, 'number') ? undefined : json['number'],
        'draftNames': !exists(json, 'draft_names') ? undefined : json['draft_names'],
    };
}

export function PatchedClusterRequestToJSON(value?: PatchedClusterRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'draft_names': value.draftNames,
    };
}

