/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize final approval information for an RfcToBe
 * @export
 * @interface PatchedFinalApprovalRequest
 */
export interface PatchedFinalApprovalRequest {
    /**
     * 
     * @type {Date}
     * @memberof PatchedFinalApprovalRequest
     */
    approved?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedFinalApprovalRequest
     */
    approverPersonId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedFinalApprovalRequest
     */
    overridingApproverPersonId?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedFinalApprovalRequest
     */
    comment?: string;
}

/**
 * Check if a given object implements the PatchedFinalApprovalRequest interface.
 */
export function instanceOfPatchedFinalApprovalRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedFinalApprovalRequestFromJSON(json: any): PatchedFinalApprovalRequest {
    return PatchedFinalApprovalRequestFromJSONTyped(json, false);
}

export function PatchedFinalApprovalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedFinalApprovalRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'approved': !exists(json, 'approved') ? undefined : (json['approved'] === null ? null : new Date(json['approved'])),
        'approverPersonId': !exists(json, 'approver_person_id') ? undefined : json['approver_person_id'],
        'overridingApproverPersonId': !exists(json, 'overriding_approver_person_id') ? undefined : json['overriding_approver_person_id'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
    };
}

export function PatchedFinalApprovalRequestToJSON(value?: PatchedFinalApprovalRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'approved': value.approved === undefined ? undefined : (value.approved === null ? null : value.approved.toISOString()),
        'approver_person_id': value.approverPersonId,
        'overriding_approver_person_id': value.overridingApproverPersonId,
        'comment': value.comment,
    };
}

