/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseDatatrackerPerson } from './BaseDatatrackerPerson';
import {
    BaseDatatrackerPersonFromJSON,
    BaseDatatrackerPersonFromJSONTyped,
    BaseDatatrackerPersonToJSON,
} from './BaseDatatrackerPerson';
import type { MinimalRfcToBe } from './MinimalRfcToBe';
import {
    MinimalRfcToBeFromJSON,
    MinimalRfcToBeFromJSONTyped,
    MinimalRfcToBeToJSON,
} from './MinimalRfcToBe';

/**
 * Serialize final approval information for an RfcToBe
 * @export
 * @interface PatchedFinalApproval
 */
export interface PatchedFinalApproval {
    /**
     * 
     * @type {number}
     * @memberof PatchedFinalApproval
     */
    id?: number;
    /**
     * 
     * @type {MinimalRfcToBe}
     * @memberof PatchedFinalApproval
     */
    rfcToBe?: MinimalRfcToBe;
    /**
     * 
     * @type {string}
     * @memberof PatchedFinalApproval
     */
    body?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedFinalApproval
     */
    requested?: Date;
    /**
     * 
     * @type {BaseDatatrackerPerson}
     * @memberof PatchedFinalApproval
     */
    approver?: BaseDatatrackerPerson;
    /**
     * 
     * @type {Date}
     * @memberof PatchedFinalApproval
     */
    approved?: Date | null;
    /**
     * 
     * @type {BaseDatatrackerPerson}
     * @memberof PatchedFinalApproval
     */
    overridingApprover?: BaseDatatrackerPerson | null;
}

/**
 * Check if a given object implements the PatchedFinalApproval interface.
 */
export function instanceOfPatchedFinalApproval(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedFinalApprovalFromJSON(json: any): PatchedFinalApproval {
    return PatchedFinalApprovalFromJSONTyped(json, false);
}

export function PatchedFinalApprovalFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedFinalApproval {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'rfcToBe': !exists(json, 'rfc_to_be') ? undefined : MinimalRfcToBeFromJSON(json['rfc_to_be']),
        'body': !exists(json, 'body') ? undefined : json['body'],
        'requested': !exists(json, 'requested') ? undefined : (new Date(json['requested'])),
        'approver': !exists(json, 'approver') ? undefined : BaseDatatrackerPersonFromJSON(json['approver']),
        'approved': !exists(json, 'approved') ? undefined : (json['approved'] === null ? null : new Date(json['approved'])),
        'overridingApprover': !exists(json, 'overriding_approver') ? undefined : BaseDatatrackerPersonFromJSON(json['overriding_approver']),
    };
}

export function PatchedFinalApprovalToJSON(value?: PatchedFinalApproval | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'rfc_to_be': MinimalRfcToBeToJSON(value.rfcToBe),
        'body': value.body,
        'requested': value.requested === undefined ? undefined : (value.requested.toISOString()),
        'approver': BaseDatatrackerPersonToJSON(value.approver),
        'approved': value.approved === undefined ? undefined : (value.approved === null ? null : value.approved.toISOString()),
        'overriding_approver': BaseDatatrackerPersonToJSON(value.overridingApprover),
    };
}

