/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ColorEnum } from './ColorEnum';
import {
    ColorEnumFromJSON,
    ColorEnumFromJSONTyped,
    ColorEnumToJSON,
} from './ColorEnum';

/**
 * 
 * @export
 * @interface PatchedLabel
 */
export interface PatchedLabel {
    /**
     * 
     * @type {number}
     * @memberof PatchedLabel
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedLabel
     */
    slug?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedLabel
     */
    isException?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedLabel
     */
    isComplexity?: boolean;
    /**
     * 
     * @type {ColorEnum}
     * @memberof PatchedLabel
     */
    color?: ColorEnum;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedLabel
     */
    used?: boolean;
}

/**
 * Check if a given object implements the PatchedLabel interface.
 */
export function instanceOfPatchedLabel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedLabelFromJSON(json: any): PatchedLabel {
    return PatchedLabelFromJSONTyped(json, false);
}

export function PatchedLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedLabel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'isException': !exists(json, 'is_exception') ? undefined : json['is_exception'],
        'isComplexity': !exists(json, 'is_complexity') ? undefined : json['is_complexity'],
        'color': !exists(json, 'color') ? undefined : ColorEnumFromJSON(json['color']),
        'used': !exists(json, 'used') ? undefined : json['used'],
    };
}

export function PatchedLabelToJSON(value?: PatchedLabel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'is_exception': value.isException,
        'is_complexity': value.isComplexity,
        'color': ColorEnumToJSON(value.color),
        'used': value.used,
    };
}

