/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for related document for an RfcToBe
 * @export
 * @interface PatchedRpcRelatedDocument
 */
export interface PatchedRpcRelatedDocument {
    /**
     * 
     * @type {number}
     * @memberof PatchedRpcRelatedDocument
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedRpcRelatedDocument
     */
    relationship?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRpcRelatedDocument
     */
    readonly draftName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRpcRelatedDocument
     */
    readonly targetDraftName?: string;
}

/**
 * Check if a given object implements the PatchedRpcRelatedDocument interface.
 */
export function instanceOfPatchedRpcRelatedDocument(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedRpcRelatedDocumentFromJSON(json: any): PatchedRpcRelatedDocument {
    return PatchedRpcRelatedDocumentFromJSONTyped(json, false);
}

export function PatchedRpcRelatedDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRpcRelatedDocument {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'relationship': !exists(json, 'relationship') ? undefined : json['relationship'],
        'draftName': !exists(json, 'draft_name') ? undefined : json['draft_name'],
        'targetDraftName': !exists(json, 'target_draft_name') ? undefined : json['target_draft_name'],
    };
}

export function PatchedRpcRelatedDocumentToJSON(value?: PatchedRpcRelatedDocument | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'relationship': value.relationship,
    };
}

