/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a SubseriesMember
 * @export
 * @interface PatchedSubseriesMember
 */
export interface PatchedSubseriesMember {
    /**
     * 
     * @type {number}
     * @memberof PatchedSubseriesMember
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedSubseriesMember
     */
    rfcToBe?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedSubseriesMember
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedSubseriesMember
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedSubseriesMember
     */
    readonly displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSubseriesMember
     */
    readonly slug?: string;
}

/**
 * Check if a given object implements the PatchedSubseriesMember interface.
 */
export function instanceOfPatchedSubseriesMember(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedSubseriesMemberFromJSON(json: any): PatchedSubseriesMember {
    return PatchedSubseriesMemberFromJSONTyped(json, false);
}

export function PatchedSubseriesMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSubseriesMember {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'rfcToBe': !exists(json, 'rfc_to_be') ? undefined : json['rfc_to_be'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
    };
}

export function PatchedSubseriesMemberToJSON(value?: PatchedSubseriesMember | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rfc_to_be': value.rfcToBe,
        'type': value.type,
        'number': value.number,
    };
}

