/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a comment on an RfcToBe
 * @export
 * @interface PatchedDocumentCommentRequest
 */
export interface PatchedDocumentCommentRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedDocumentCommentRequest
     */
    comment?: string;
}

/**
 * Check if a given object implements the PatchedDocumentCommentRequest interface.
 */
export function instanceOfPatchedDocumentCommentRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedDocumentCommentRequestFromJSON(json: any): PatchedDocumentCommentRequest {
    return PatchedDocumentCommentRequestFromJSONTyped(json, false);
}

export function PatchedDocumentCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedDocumentCommentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
    };
}

export function PatchedDocumentCommentRequestToJSON(value?: PatchedDocumentCommentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
    };
}

