/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StateEnum } from './StateEnum';
import {
    StateEnumFromJSON,
    StateEnumFromJSONTyped,
    StateEnumToJSON,
} from './StateEnum';

/**
 * Assignment serializer with PK reference to RfcToBe
 * @export
 * @interface PatchedAssignmentRequest
 */
export interface PatchedAssignmentRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedAssignmentRequest
     */
    rfcToBe?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedAssignmentRequest
     */
    person?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedAssignmentRequest
     */
    role?: string;
    /**
     * 
     * @type {StateEnum}
     * @memberof PatchedAssignmentRequest
     */
    state?: StateEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedAssignmentRequest
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAssignmentRequest
     */
    timeSpent?: string;
}

/**
 * Check if a given object implements the PatchedAssignmentRequest interface.
 */
export function instanceOfPatchedAssignmentRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedAssignmentRequestFromJSON(json: any): PatchedAssignmentRequest {
    return PatchedAssignmentRequestFromJSONTyped(json, false);
}

export function PatchedAssignmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedAssignmentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rfcToBe': !exists(json, 'rfc_to_be') ? undefined : json['rfc_to_be'],
        'person': !exists(json, 'person') ? undefined : json['person'],
        'role': !exists(json, 'role') ? undefined : json['role'],
        'state': !exists(json, 'state') ? undefined : StateEnumFromJSON(json['state']),
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'timeSpent': !exists(json, 'time_spent') ? undefined : json['time_spent'],
    };
}

export function PatchedAssignmentRequestToJSON(value?: PatchedAssignmentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rfc_to_be': value.rfcToBe,
        'person': value.person,
        'role': value.role,
        'state': StateEnumToJSON(value.state),
        'comment': value.comment,
        'time_spent': value.timeSpent,
    };
}

