/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedApprovalLogMessageRequest
 */
export interface PatchedApprovalLogMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedApprovalLogMessageRequest
     */
    logMessage?: string;
}

/**
 * Check if a given object implements the PatchedApprovalLogMessageRequest interface.
 */
export function instanceOfPatchedApprovalLogMessageRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedApprovalLogMessageRequestFromJSON(json: any): PatchedApprovalLogMessageRequest {
    return PatchedApprovalLogMessageRequestFromJSONTyped(json, false);
}

export function PatchedApprovalLogMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedApprovalLogMessageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'logMessage': !exists(json, 'log_message') ? undefined : json['log_message'],
    };
}

export function PatchedApprovalLogMessageRequestToJSON(value?: PatchedApprovalLogMessageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'log_message': value.logMessage,
    };
}

