/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedRfcAuthorRequest
 */
export interface PatchedRfcAuthorRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcAuthorRequest
     */
    titlepageName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedRfcAuthorRequest
     */
    isEditor?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcAuthorRequest
     */
    affiliation?: string | null;
}

/**
 * Check if a given object implements the PatchedRfcAuthorRequest interface.
 */
export function instanceOfPatchedRfcAuthorRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedRfcAuthorRequestFromJSON(json: any): PatchedRfcAuthorRequest {
    return PatchedRfcAuthorRequestFromJSONTyped(json, false);
}

export function PatchedRfcAuthorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRfcAuthorRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'titlepageName': !exists(json, 'titlepage_name') ? undefined : json['titlepage_name'],
        'isEditor': !exists(json, 'is_editor') ? undefined : json['is_editor'],
        'affiliation': !exists(json, 'affiliation') ? undefined : json['affiliation'],
    };
}

export function PatchedRfcAuthorRequestToJSON(value?: PatchedRfcAuthorRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'titlepage_name': value.titlepageName,
        'is_editor': value.isEditor,
        'affiliation': value.affiliation,
    };
}

