/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActionHolder } from './ActionHolder';
import {
    ActionHolderFromJSON,
    ActionHolderFromJSONTyped,
    ActionHolderToJSON,
} from './ActionHolder';
import type { Assignment } from './Assignment';
import {
    AssignmentFromJSON,
    AssignmentFromJSONTyped,
    AssignmentToJSON,
} from './Assignment';
import type { Draft } from './Draft';
import {
    DraftFromJSON,
    DraftFromJSONTyped,
    DraftToJSON,
} from './Draft';
import type { RfcAuthor } from './RfcAuthor';
import {
    RfcAuthorFromJSON,
    RfcAuthorFromJSONTyped,
    RfcAuthorToJSON,
} from './RfcAuthor';
import type { RpcRole } from './RpcRole';
import {
    RpcRoleFromJSON,
    RpcRoleFromJSONTyped,
    RpcRoleToJSON,
} from './RpcRole';
import type { SimpleCluster } from './SimpleCluster';
import {
    SimpleClusterFromJSON,
    SimpleClusterFromJSONTyped,
    SimpleClusterToJSON,
} from './SimpleCluster';
import type { SubseriesMember } from './SubseriesMember';
import {
    SubseriesMemberFromJSON,
    SubseriesMemberFromJSONTyped,
    SubseriesMemberToJSON,
} from './SubseriesMember';

/**
 * RfcToBeSerializer suitable for displaying full details of a single instance
 * @export
 * @interface PatchedRfcToBe
 */
export interface PatchedRfcToBe {
    /**
     * 
     * @type {number}
     * @memberof PatchedRfcToBe
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcToBe
     */
    readonly name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcToBe
     */
    readonly title?: string;
    /**
     * 
     * @type {Draft}
     * @memberof PatchedRfcToBe
     */
    readonly draft?: Draft;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcToBe
     */
    disposition?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRfcToBe
     */
    externalDeadline?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRfcToBe
     */
    internalGoal?: Date | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchedRfcToBe
     */
    labels?: Array<number>;
    /**
     * 
     * @type {SimpleCluster}
     * @memberof PatchedRfcToBe
     */
    readonly cluster?: SimpleCluster;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcToBe
     */
    submittedFormat?: string;
    /**
     * TLP IPR boilerplate option applicable when document entered the queue
     * @type {string}
     * @memberof PatchedRfcToBe
     */
    submittedBoilerplate?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcToBe
     */
    submittedStdLevel?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcToBe
     */
    submittedStream?: string;
    /**
     * TLP IPR boilerplate option intended to apply upon publication as RFC
     * @type {string}
     * @memberof PatchedRfcToBe
     */
    intendedBoilerplate?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcToBe
     */
    intendedStdLevel?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcToBe
     */
    intendedStream?: string;
    /**
     * 
     * @type {Array<RfcAuthor>}
     * @memberof PatchedRfcToBe
     */
    authors?: Array<RfcAuthor>;
    /**
     * 
     * @type {Array<Assignment>}
     * @memberof PatchedRfcToBe
     */
    readonly assignmentSet?: Array<Assignment>;
    /**
     * 
     * @type {Array<ActionHolder>}
     * @memberof PatchedRfcToBe
     */
    readonly actionholderSet?: Array<ActionHolder>;
    /**
     * 
     * @type {Array<RpcRole>}
     * @memberof PatchedRfcToBe
     */
    readonly pendingActivities?: Array<RpcRole>;
    /**
     * 
     * @type {number}
     * @memberof PatchedRfcToBe
     */
    rfcNumber?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRfcToBe
     */
    readonly publishedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedRfcToBe
     */
    readonly consensus?: boolean;
    /**
     * 
     * @type {Array<SubseriesMember>}
     * @memberof PatchedRfcToBe
     */
    readonly subseries?: Array<SubseriesMember>;
}

/**
 * Check if a given object implements the PatchedRfcToBe interface.
 */
export function instanceOfPatchedRfcToBe(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedRfcToBeFromJSON(json: any): PatchedRfcToBe {
    return PatchedRfcToBeFromJSONTyped(json, false);
}

export function PatchedRfcToBeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRfcToBe {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'draft': !exists(json, 'draft') ? undefined : DraftFromJSON(json['draft']),
        'disposition': !exists(json, 'disposition') ? undefined : json['disposition'],
        'externalDeadline': !exists(json, 'external_deadline') ? undefined : (json['external_deadline'] === null ? null : new Date(json['external_deadline'])),
        'internalGoal': !exists(json, 'internal_goal') ? undefined : (json['internal_goal'] === null ? null : new Date(json['internal_goal'])),
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
        'cluster': !exists(json, 'cluster') ? undefined : SimpleClusterFromJSON(json['cluster']),
        'submittedFormat': !exists(json, 'submitted_format') ? undefined : json['submitted_format'],
        'submittedBoilerplate': !exists(json, 'submitted_boilerplate') ? undefined : json['submitted_boilerplate'],
        'submittedStdLevel': !exists(json, 'submitted_std_level') ? undefined : json['submitted_std_level'],
        'submittedStream': !exists(json, 'submitted_stream') ? undefined : json['submitted_stream'],
        'intendedBoilerplate': !exists(json, 'intended_boilerplate') ? undefined : json['intended_boilerplate'],
        'intendedStdLevel': !exists(json, 'intended_std_level') ? undefined : json['intended_std_level'],
        'intendedStream': !exists(json, 'intended_stream') ? undefined : json['intended_stream'],
        'authors': !exists(json, 'authors') ? undefined : ((json['authors'] as Array<any>).map(RfcAuthorFromJSON)),
        'assignmentSet': !exists(json, 'assignment_set') ? undefined : ((json['assignment_set'] as Array<any>).map(AssignmentFromJSON)),
        'actionholderSet': !exists(json, 'actionholder_set') ? undefined : ((json['actionholder_set'] as Array<any>).map(ActionHolderFromJSON)),
        'pendingActivities': !exists(json, 'pending_activities') ? undefined : ((json['pending_activities'] as Array<any>).map(RpcRoleFromJSON)),
        'rfcNumber': !exists(json, 'rfc_number') ? undefined : json['rfc_number'],
        'publishedAt': !exists(json, 'published_at') ? undefined : (json['published_at'] === null ? null : new Date(json['published_at'])),
        'consensus': !exists(json, 'consensus') ? undefined : json['consensus'],
        'subseries': !exists(json, 'subseries') ? undefined : ((json['subseries'] as Array<any>).map(SubseriesMemberFromJSON)),
    };
}

export function PatchedRfcToBeToJSON(value?: PatchedRfcToBe | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'disposition': value.disposition,
        'external_deadline': value.externalDeadline === undefined ? undefined : (value.externalDeadline === null ? null : value.externalDeadline.toISOString()),
        'internal_goal': value.internalGoal === undefined ? undefined : (value.internalGoal === null ? null : value.internalGoal.toISOString()),
        'labels': value.labels,
        'submitted_format': value.submittedFormat,
        'submitted_boilerplate': value.submittedBoilerplate,
        'submitted_std_level': value.submittedStdLevel,
        'submitted_stream': value.submittedStream,
        'intended_boilerplate': value.intendedBoilerplate,
        'intended_std_level': value.intendedStdLevel,
        'intended_stream': value.intendedStream,
        'authors': value.authors === undefined ? undefined : ((value.authors as Array<any>).map(RfcAuthorToJSON)),
        'rfc_number': value.rfcNumber,
    };
}

