/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize an Unusable Rfc Number
 * @export
 * @interface PatchedUnusableRfcNumberRequest
 */
export interface PatchedUnusableRfcNumberRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedUnusableRfcNumberRequest
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedUnusableRfcNumberRequest
     */
    comment?: string;
}

/**
 * Check if a given object implements the PatchedUnusableRfcNumberRequest interface.
 */
export function instanceOfPatchedUnusableRfcNumberRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedUnusableRfcNumberRequestFromJSON(json: any): PatchedUnusableRfcNumberRequest {
    return PatchedUnusableRfcNumberRequestFromJSONTyped(json, false);
}

export function PatchedUnusableRfcNumberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUnusableRfcNumberRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': !exists(json, 'number') ? undefined : json['number'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
    };
}

export function PatchedUnusableRfcNumberRequestToJSON(value?: PatchedUnusableRfcNumberRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'comment': value.comment,
    };
}

