/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IanaStatusSlugEnum } from './IanaStatusSlugEnum';
import {
    IanaStatusSlugEnumFromJSON,
    IanaStatusSlugEnumFromJSONTyped,
    IanaStatusSlugEnumToJSON,
} from './IanaStatusSlugEnum';
import type { RfcAuthorRequest } from './RfcAuthorRequest';
import {
    RfcAuthorRequestFromJSON,
    RfcAuthorRequestFromJSONTyped,
    RfcAuthorRequestToJSON,
} from './RfcAuthorRequest';

/**
 * RfcToBeSerializer suitable for displaying full details of a single instance
 * @export
 * @interface PatchedRfcToBeRequest
 */
export interface PatchedRfcToBeRequest {
    /**
     * Document title
     * @type {string}
     * @memberof PatchedRfcToBeRequest
     */
    title?: string;
    /**
     * Document abstract
     * @type {string}
     * @memberof PatchedRfcToBeRequest
     */
    _abstract?: string;
    /**
     * Acronym of datatracker group where this document originated, if any
     * @type {string}
     * @memberof PatchedRfcToBeRequest
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcToBeRequest
     */
    disposition?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRfcToBeRequest
     */
    externalDeadline?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRfcToBeRequest
     */
    internalGoal?: Date | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchedRfcToBeRequest
     */
    labels?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof PatchedRfcToBeRequest
     */
    submittedFormat?: string;
    /**
     * Page count
     * @type {number}
     * @memberof PatchedRfcToBeRequest
     */
    pages?: number | null;
    /**
     * Comma-separated list of keywords
     * @type {string}
     * @memberof PatchedRfcToBeRequest
     */
    keywords?: string;
    /**
     * TLP IPR boilerplate option
     * @type {string}
     * @memberof PatchedRfcToBeRequest
     */
    boilerplate?: string;
    /**
     * Current StdLevel
     * @type {string}
     * @memberof PatchedRfcToBeRequest
     */
    stdLevel?: string;
    /**
     * StdLevel at publication (blank until published)
     * @type {string}
     * @memberof PatchedRfcToBeRequest
     */
    publicationStdLevel?: string | null;
    /**
     * Current stream
     * @type {string}
     * @memberof PatchedRfcToBeRequest
     */
    stream?: string;
    /**
     * Stream at publication (blank until published)
     * @type {string}
     * @memberof PatchedRfcToBeRequest
     */
    publicationStream?: string | null;
    /**
     * 
     * @type {Array<RfcAuthorRequest>}
     * @memberof PatchedRfcToBeRequest
     */
    authors?: Array<RfcAuthorRequest>;
    /**
     * 
     * @type {number}
     * @memberof PatchedRfcToBeRequest
     */
    rfcNumber?: number | null;
    /**
     * Whether document has consensus (None=unknown)
     * @type {boolean}
     * @memberof PatchedRfcToBeRequest
     */
    consensus?: boolean | null;
    /**
     * 
     * @type {IanaStatusSlugEnum}
     * @memberof PatchedRfcToBeRequest
     */
    ianaStatusSlug?: IanaStatusSlugEnum;
}

/**
 * Check if a given object implements the PatchedRfcToBeRequest interface.
 */
export function instanceOfPatchedRfcToBeRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedRfcToBeRequestFromJSON(json: any): PatchedRfcToBeRequest {
    return PatchedRfcToBeRequestFromJSONTyped(json, false);
}

export function PatchedRfcToBeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRfcToBeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        '_abstract': !exists(json, 'abstract') ? undefined : json['abstract'],
        'group': !exists(json, 'group') ? undefined : json['group'],
        'disposition': !exists(json, 'disposition') ? undefined : json['disposition'],
        'externalDeadline': !exists(json, 'external_deadline') ? undefined : (json['external_deadline'] === null ? null : new Date(json['external_deadline'])),
        'internalGoal': !exists(json, 'internal_goal') ? undefined : (json['internal_goal'] === null ? null : new Date(json['internal_goal'])),
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
        'submittedFormat': !exists(json, 'submitted_format') ? undefined : json['submitted_format'],
        'pages': !exists(json, 'pages') ? undefined : json['pages'],
        'keywords': !exists(json, 'keywords') ? undefined : json['keywords'],
        'boilerplate': !exists(json, 'boilerplate') ? undefined : json['boilerplate'],
        'stdLevel': !exists(json, 'std_level') ? undefined : json['std_level'],
        'publicationStdLevel': !exists(json, 'publication_std_level') ? undefined : json['publication_std_level'],
        'stream': !exists(json, 'stream') ? undefined : json['stream'],
        'publicationStream': !exists(json, 'publication_stream') ? undefined : json['publication_stream'],
        'authors': !exists(json, 'authors') ? undefined : ((json['authors'] as Array<any>).map(RfcAuthorRequestFromJSON)),
        'rfcNumber': !exists(json, 'rfc_number') ? undefined : json['rfc_number'],
        'consensus': !exists(json, 'consensus') ? undefined : json['consensus'],
        'ianaStatusSlug': !exists(json, 'iana_status_slug') ? undefined : IanaStatusSlugEnumFromJSON(json['iana_status_slug']),
    };
}

export function PatchedRfcToBeRequestToJSON(value?: PatchedRfcToBeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'abstract': value._abstract,
        'group': value.group,
        'disposition': value.disposition,
        'external_deadline': value.externalDeadline === undefined ? undefined : (value.externalDeadline === null ? null : value.externalDeadline.toISOString()),
        'internal_goal': value.internalGoal === undefined ? undefined : (value.internalGoal === null ? null : value.internalGoal.toISOString()),
        'labels': value.labels,
        'submitted_format': value.submittedFormat,
        'pages': value.pages,
        'keywords': value.keywords,
        'boilerplate': value.boilerplate,
        'std_level': value.stdLevel,
        'publication_std_level': value.publicationStdLevel,
        'stream': value.stream,
        'publication_stream': value.publicationStream,
        'authors': value.authors === undefined ? undefined : ((value.authors as Array<any>).map(RfcAuthorRequestToJSON)),
        'rfc_number': value.rfcNumber,
        'consensus': value.consensus,
        'iana_status_slug': IanaStatusSlugEnumToJSON(value.ianaStatusSlug),
    };
}

