/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize an Unusable Rfc Number
 * @export
 * @interface PatchedUnusableRfcNumber
 */
export interface PatchedUnusableRfcNumber {
    /**
     * 
     * @type {number}
     * @memberof PatchedUnusableRfcNumber
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedUnusableRfcNumber
     */
    comment?: string;
}

/**
 * Check if a given object implements the PatchedUnusableRfcNumber interface.
 */
export function instanceOfPatchedUnusableRfcNumber(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedUnusableRfcNumberFromJSON(json: any): PatchedUnusableRfcNumber {
    return PatchedUnusableRfcNumberFromJSONTyped(json, false);
}

export function PatchedUnusableRfcNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUnusableRfcNumber {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': !exists(json, 'number') ? undefined : json['number'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
    };
}

export function PatchedUnusableRfcNumberToJSON(value?: PatchedUnusableRfcNumber | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'comment': value.comment,
    };
}

