/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for related document for an RfcToBe
 * @export
 * @interface PatchedRpcRelatedDocumentRequest
 */
export interface PatchedRpcRelatedDocumentRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedRpcRelatedDocumentRequest
     */
    relationship?: string;
}

/**
 * Check if a given object implements the PatchedRpcRelatedDocumentRequest interface.
 */
export function instanceOfPatchedRpcRelatedDocumentRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedRpcRelatedDocumentRequestFromJSON(json: any): PatchedRpcRelatedDocumentRequest {
    return PatchedRpcRelatedDocumentRequestFromJSONTyped(json, false);
}

export function PatchedRpcRelatedDocumentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRpcRelatedDocumentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'relationship': !exists(json, 'relationship') ? undefined : json['relationship'],
    };
}

export function PatchedRpcRelatedDocumentRequestToJSON(value?: PatchedRpcRelatedDocumentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'relationship': value.relationship,
    };
}

