/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {boolean}
     * @memberof Profile
     */
    authenticated: boolean;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    avatar: string;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    rpcPersonId: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Profile
     */
    isManager: boolean;
}

/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authenticated" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "avatar" in value;
    isInstance = isInstance && "rpcPersonId" in value;
    isInstance = isInstance && "isManager" in value;

    return isInstance;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authenticated': json['authenticated'],
        'id': json['id'],
        'name': json['name'],
        'avatar': json['avatar'],
        'rpcPersonId': json['rpcPersonId'],
        'isManager': json['isManager'],
    };
}

export function ProfileToJSON(value?: Profile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authenticated': value.authenticated,
        'id': value.id,
        'name': value.name,
        'avatar': value.avatar,
        'rpcPersonId': value.rpcPersonId,
        'isManager': value.isManager,
    };
}

