/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublishRfcRequest
 */
export interface PublishRfcRequest {
    /**
     * Commit hash of repository HEAD intended for publication
     * @type {string}
     * @memberof PublishRfcRequest
     */
    headSha: string;
}

/**
 * Check if a given object implements the PublishRfcRequest interface.
 */
export function instanceOfPublishRfcRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "headSha" in value;

    return isInstance;
}

export function PublishRfcRequestFromJSON(json: any): PublishRfcRequest {
    return PublishRfcRequestFromJSONTyped(json, false);
}

export function PublishRfcRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishRfcRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'headSha': json['head_sha'],
    };
}

export function PublishRfcRequestToJSON(value?: PublishRfcRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'head_sha': value.headSha,
    };
}

