/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StateEnum } from './StateEnum';
import {
    StateEnumFromJSON,
    StateEnumFromJSONTyped,
    StateEnumToJSON,
} from './StateEnum';

/**
 * Assignment serializer for the public queue view
 * @export
 * @interface PublicAssignment
 */
export interface PublicAssignment {
    /**
     * 
     * @type {number}
     * @memberof PublicAssignment
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof PublicAssignment
     */
    rfcToBe: number;
    /**
     * 
     * @type {string}
     * @memberof PublicAssignment
     */
    role: string;
    /**
     * 
     * @type {StateEnum}
     * @memberof PublicAssignment
     */
    state?: StateEnum;
}

/**
 * Check if a given object implements the PublicAssignment interface.
 */
export function instanceOfPublicAssignment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rfcToBe" in value;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function PublicAssignmentFromJSON(json: any): PublicAssignment {
    return PublicAssignmentFromJSONTyped(json, false);
}

export function PublicAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicAssignment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'rfcToBe': json['rfc_to_be'],
        'role': json['role'],
        'state': !exists(json, 'state') ? undefined : StateEnumFromJSON(json['state']),
    };
}

export function PublicAssignmentToJSON(value?: PublicAssignment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rfc_to_be': value.rfcToBe,
        'role': value.role,
        'state': StateEnumToJSON(value.state),
    };
}

