/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicQueueAuthor
 */
export interface PublicQueueAuthor {
    /**
     * 
     * @type {string}
     * @memberof PublicQueueAuthor
     */
    titlepageName: string;
    /**
     * 
     * @type {boolean}
     * @memberof PublicQueueAuthor
     */
    isEditor?: boolean;
}

/**
 * Check if a given object implements the PublicQueueAuthor interface.
 */
export function instanceOfPublicQueueAuthor(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "titlepageName" in value;

    return isInstance;
}

export function PublicQueueAuthorFromJSON(json: any): PublicQueueAuthor {
    return PublicQueueAuthorFromJSONTyped(json, false);
}

export function PublicQueueAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicQueueAuthor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'titlepageName': json['titlepage_name'],
        'isEditor': !exists(json, 'is_editor') ? undefined : json['is_editor'],
    };
}

export function PublicQueueAuthorToJSON(value?: PublicQueueAuthor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'titlepage_name': value.titlepageName,
        'is_editor': value.isEditor,
    };
}

