/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActionHolder } from './ActionHolder';
import {
    ActionHolderFromJSON,
    ActionHolderFromJSONTyped,
    ActionHolderToJSON,
} from './ActionHolder';
import type { FinalApproval } from './FinalApproval';
import {
    FinalApprovalFromJSON,
    FinalApprovalFromJSONTyped,
    FinalApprovalToJSON,
} from './FinalApproval';
import type { IanaStatus } from './IanaStatus';
import {
    IanaStatusFromJSON,
    IanaStatusFromJSONTyped,
    IanaStatusToJSON,
} from './IanaStatus';
import type { Label } from './Label';
import {
    LabelFromJSON,
    LabelFromJSONTyped,
    LabelToJSON,
} from './Label';
import type { PublicAssignment } from './PublicAssignment';
import {
    PublicAssignmentFromJSON,
    PublicAssignmentFromJSONTyped,
    PublicAssignmentToJSON,
} from './PublicAssignment';
import type { PublicQueueAuthor } from './PublicQueueAuthor';
import {
    PublicQueueAuthorFromJSON,
    PublicQueueAuthorFromJSONTyped,
    PublicQueueAuthorToJSON,
} from './PublicQueueAuthor';
import type { RfcToBeBlockingReason } from './RfcToBeBlockingReason';
import {
    RfcToBeBlockingReasonFromJSON,
    RfcToBeBlockingReasonFromJSONTyped,
    RfcToBeBlockingReasonToJSON,
} from './RfcToBeBlockingReason';
import type { RpcRole } from './RpcRole';
import {
    RpcRoleFromJSON,
    RpcRoleFromJSONTyped,
    RpcRoleToJSON,
} from './RpcRole';
import type { SimpleCluster } from './SimpleCluster';
import {
    SimpleClusterFromJSON,
    SimpleClusterFromJSONTyped,
    SimpleClusterToJSON,
} from './SimpleCluster';

/**
 * RfcToBe serializer for the public view of the RFC Editor queue
 * @export
 * @interface PublicQueueItem
 */
export interface PublicQueueItem {
    /**
     * 
     * @type {number}
     * @memberof PublicQueueItem
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PublicQueueItem
     */
    readonly name?: string;
    /**
     * Document title
     * @type {string}
     * @memberof PublicQueueItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PublicQueueItem
     */
    draftUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicQueueItem
     */
    disposition: string;
    /**
     * 
     * @type {Date}
     * @memberof PublicQueueItem
     */
    externalDeadline?: Date | null;
    /**
     * 
     * @type {Array<Label>}
     * @memberof PublicQueueItem
     */
    readonly labels?: Array<Label>;
    /**
     * 
     * @type {SimpleCluster}
     * @memberof PublicQueueItem
     */
    readonly cluster?: SimpleCluster;
    /**
     * 
     * @type {Array<PublicAssignment>}
     * @memberof PublicQueueItem
     */
    readonly assignmentSet?: Array<PublicAssignment>;
    /**
     * 
     * @type {Array<ActionHolder>}
     * @memberof PublicQueueItem
     */
    readonly actionholderSet?: Array<ActionHolder>;
    /**
     * 
     * @type {Array<RpcRole>}
     * @memberof PublicQueueItem
     */
    readonly pendingActivities?: Array<RpcRole>;
    /**
     * 
     * @type {number}
     * @memberof PublicQueueItem
     */
    rfcNumber?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PublicQueueItem
     */
    readonly pages?: number;
    /**
     * Datetime document entered the queue
     * @type {Date}
     * @memberof PublicQueueItem
     */
    enqueuedAt: Date;
    /**
     * 
     * @type {Array<FinalApproval>}
     * @memberof PublicQueueItem
     */
    readonly finalApproval?: Array<FinalApproval>;
    /**
     * 
     * @type {IanaStatus}
     * @memberof PublicQueueItem
     */
    readonly ianaStatus?: IanaStatus;
    /**
     * 
     * @type {Array<RfcToBeBlockingReason>}
     * @memberof PublicQueueItem
     */
    readonly blockingReasons?: Array<RfcToBeBlockingReason>;
    /**
     * 
     * @type {Array<PublicQueueAuthor>}
     * @memberof PublicQueueItem
     */
    authors: Array<PublicQueueAuthor>;
}

/**
 * Check if a given object implements the PublicQueueItem interface.
 */
export function instanceOfPublicQueueItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "draftUrl" in value;
    isInstance = isInstance && "disposition" in value;
    isInstance = isInstance && "enqueuedAt" in value;
    isInstance = isInstance && "authors" in value;

    return isInstance;
}

export function PublicQueueItemFromJSON(json: any): PublicQueueItem {
    return PublicQueueItemFromJSONTyped(json, false);
}

export function PublicQueueItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicQueueItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'title': json['title'],
        'draftUrl': json['draft_url'],
        'disposition': json['disposition'],
        'externalDeadline': !exists(json, 'external_deadline') ? undefined : (json['external_deadline'] === null ? null : new Date(json['external_deadline'])),
        'labels': !exists(json, 'labels') ? undefined : ((json['labels'] as Array<any>).map(LabelFromJSON)),
        'cluster': !exists(json, 'cluster') ? undefined : SimpleClusterFromJSON(json['cluster']),
        'assignmentSet': !exists(json, 'assignment_set') ? undefined : ((json['assignment_set'] as Array<any>).map(PublicAssignmentFromJSON)),
        'actionholderSet': !exists(json, 'actionholder_set') ? undefined : ((json['actionholder_set'] as Array<any>).map(ActionHolderFromJSON)),
        'pendingActivities': !exists(json, 'pending_activities') ? undefined : ((json['pending_activities'] as Array<any>).map(RpcRoleFromJSON)),
        'rfcNumber': !exists(json, 'rfc_number') ? undefined : json['rfc_number'],
        'pages': !exists(json, 'pages') ? undefined : json['pages'],
        'enqueuedAt': (new Date(json['enqueued_at'])),
        'finalApproval': !exists(json, 'final_approval') ? undefined : ((json['final_approval'] as Array<any>).map(FinalApprovalFromJSON)),
        'ianaStatus': !exists(json, 'iana_status') ? undefined : IanaStatusFromJSON(json['iana_status']),
        'blockingReasons': !exists(json, 'blocking_reasons') ? undefined : ((json['blocking_reasons'] as Array<any>).map(RfcToBeBlockingReasonFromJSON)),
        'authors': ((json['authors'] as Array<any>).map(PublicQueueAuthorFromJSON)),
    };
}

export function PublicQueueItemToJSON(value?: PublicQueueItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'draft_url': value.draftUrl,
        'disposition': value.disposition,
        'external_deadline': value.externalDeadline === undefined ? undefined : (value.externalDeadline === null ? null : value.externalDeadline.toISOString()),
        'rfc_number': value.rfcNumber,
        'enqueued_at': (value.enqueuedAt.toISOString()),
        'authors': ((value.authors as Array<any>).map(PublicQueueAuthorToJSON)),
    };
}

