/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RfcAuthorRequest
 */
export interface RfcAuthorRequest {
    /**
     * 
     * @type {string}
     * @memberof RfcAuthorRequest
     */
    titlepageName: string;
    /**
     * 
     * @type {boolean}
     * @memberof RfcAuthorRequest
     */
    isEditor?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RfcAuthorRequest
     */
    affiliation?: string | null;
}

/**
 * Check if a given object implements the RfcAuthorRequest interface.
 */
export function instanceOfRfcAuthorRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "titlepageName" in value;

    return isInstance;
}

export function RfcAuthorRequestFromJSON(json: any): RfcAuthorRequest {
    return RfcAuthorRequestFromJSONTyped(json, false);
}

export function RfcAuthorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RfcAuthorRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'titlepageName': json['titlepage_name'],
        'isEditor': !exists(json, 'is_editor') ? undefined : json['is_editor'],
        'affiliation': !exists(json, 'affiliation') ? undefined : json['affiliation'],
    };
}

export function RfcAuthorRequestToJSON(value?: RfcAuthorRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'titlepage_name': value.titlepageName,
        'is_editor': value.isEditor,
        'affiliation': value.affiliation,
    };
}

