/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActionHolder } from './ActionHolder';
import {
    ActionHolderFromJSON,
    ActionHolderFromJSONTyped,
    ActionHolderToJSON,
} from './ActionHolder';
import type { Assignment } from './Assignment';
import {
    AssignmentFromJSON,
    AssignmentFromJSONTyped,
    AssignmentToJSON,
} from './Assignment';
import type { BaseDatatrackerPerson } from './BaseDatatrackerPerson';
import {
    BaseDatatrackerPersonFromJSON,
    BaseDatatrackerPersonFromJSONTyped,
    BaseDatatrackerPersonToJSON,
} from './BaseDatatrackerPerson';
import type { Draft } from './Draft';
import {
    DraftFromJSON,
    DraftFromJSONTyped,
    DraftToJSON,
} from './Draft';
import type { IanaStatus } from './IanaStatus';
import {
    IanaStatusFromJSON,
    IanaStatusFromJSONTyped,
    IanaStatusToJSON,
} from './IanaStatus';
import type { RfcAuthor } from './RfcAuthor';
import {
    RfcAuthorFromJSON,
    RfcAuthorFromJSONTyped,
    RfcAuthorToJSON,
} from './RfcAuthor';
import type { RpcRole } from './RpcRole';
import {
    RpcRoleFromJSON,
    RpcRoleFromJSONTyped,
    RpcRoleToJSON,
} from './RpcRole';
import type { SimpleCluster } from './SimpleCluster';
import {
    SimpleClusterFromJSON,
    SimpleClusterFromJSONTyped,
    SimpleClusterToJSON,
} from './SimpleCluster';
import type { SubseriesMember } from './SubseriesMember';
import {
    SubseriesMemberFromJSON,
    SubseriesMemberFromJSONTyped,
    SubseriesMemberToJSON,
} from './SubseriesMember';

/**
 * RfcToBeSerializer suitable for displaying full details of a single instance
 * @export
 * @interface RfcToBe
 */
export interface RfcToBe {
    /**
     * 
     * @type {number}
     * @memberof RfcToBe
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof RfcToBe
     */
    readonly name?: string;
    /**
     * Document title
     * @type {string}
     * @memberof RfcToBe
     */
    title: string;
    /**
     * Document abstract
     * @type {string}
     * @memberof RfcToBe
     */
    _abstract?: string;
    /**
     * Acronym of datatracker group where this document originated, if any
     * @type {string}
     * @memberof RfcToBe
     */
    group?: string;
    /**
     * 
     * @type {Draft}
     * @memberof RfcToBe
     */
    readonly draft?: Draft;
    /**
     * 
     * @type {string}
     * @memberof RfcToBe
     */
    disposition: string;
    /**
     * 
     * @type {Date}
     * @memberof RfcToBe
     */
    externalDeadline?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RfcToBe
     */
    internalGoal?: Date | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof RfcToBe
     */
    labels: Array<number>;
    /**
     * 
     * @type {SimpleCluster}
     * @memberof RfcToBe
     */
    readonly cluster?: SimpleCluster;
    /**
     * 
     * @type {string}
     * @memberof RfcToBe
     */
    submittedFormat: string;
    /**
     * Page count
     * @type {number}
     * @memberof RfcToBe
     */
    pages?: number | null;
    /**
     * Comma-separated list of keywords
     * @type {string}
     * @memberof RfcToBe
     */
    keywords?: string;
    /**
     * TLP IPR boilerplate option
     * @type {string}
     * @memberof RfcToBe
     */
    boilerplate: string;
    /**
     * Current StdLevel
     * @type {string}
     * @memberof RfcToBe
     */
    stdLevel: string;
    /**
     * StdLevel at publication (blank until published)
     * @type {string}
     * @memberof RfcToBe
     */
    publicationStdLevel?: string | null;
    /**
     * Current stream
     * @type {string}
     * @memberof RfcToBe
     */
    stream: string;
    /**
     * Stream at publication (blank until published)
     * @type {string}
     * @memberof RfcToBe
     */
    publicationStream?: string | null;
    /**
     * 
     * @type {Array<RfcAuthor>}
     * @memberof RfcToBe
     */
    authors: Array<RfcAuthor>;
    /**
     * 
     * @type {BaseDatatrackerPerson}
     * @memberof RfcToBe
     */
    readonly shepherd?: BaseDatatrackerPerson;
    /**
     * 
     * @type {BaseDatatrackerPerson}
     * @memberof RfcToBe
     */
    readonly iesgContact?: BaseDatatrackerPerson;
    /**
     * 
     * @type {Array<Assignment>}
     * @memberof RfcToBe
     */
    readonly assignmentSet?: Array<Assignment>;
    /**
     * 
     * @type {Array<ActionHolder>}
     * @memberof RfcToBe
     */
    readonly actionholderSet?: Array<ActionHolder>;
    /**
     * 
     * @type {Array<RpcRole>}
     * @memberof RfcToBe
     */
    readonly pendingActivities?: Array<RpcRole>;
    /**
     * 
     * @type {number}
     * @memberof RfcToBe
     */
    rfcNumber?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof RfcToBe
     */
    readonly publishedAt?: Date | null;
    /**
     * Whether document has consensus (None=unknown)
     * @type {boolean}
     * @memberof RfcToBe
     */
    consensus?: boolean | null;
    /**
     * 
     * @type {Array<SubseriesMember>}
     * @memberof RfcToBe
     */
    readonly subseries?: Array<SubseriesMember>;
    /**
     * 
     * @type {IanaStatus}
     * @memberof RfcToBe
     */
    readonly ianaStatus?: IanaStatus;
}

/**
 * Check if a given object implements the RfcToBe interface.
 */
export function instanceOfRfcToBe(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "disposition" in value;
    isInstance = isInstance && "labels" in value;
    isInstance = isInstance && "submittedFormat" in value;
    isInstance = isInstance && "boilerplate" in value;
    isInstance = isInstance && "stdLevel" in value;
    isInstance = isInstance && "stream" in value;
    isInstance = isInstance && "authors" in value;

    return isInstance;
}

export function RfcToBeFromJSON(json: any): RfcToBe {
    return RfcToBeFromJSONTyped(json, false);
}

export function RfcToBeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RfcToBe {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'title': json['title'],
        '_abstract': !exists(json, 'abstract') ? undefined : json['abstract'],
        'group': !exists(json, 'group') ? undefined : json['group'],
        'draft': !exists(json, 'draft') ? undefined : DraftFromJSON(json['draft']),
        'disposition': json['disposition'],
        'externalDeadline': !exists(json, 'external_deadline') ? undefined : (json['external_deadline'] === null ? null : new Date(json['external_deadline'])),
        'internalGoal': !exists(json, 'internal_goal') ? undefined : (json['internal_goal'] === null ? null : new Date(json['internal_goal'])),
        'labels': json['labels'],
        'cluster': !exists(json, 'cluster') ? undefined : SimpleClusterFromJSON(json['cluster']),
        'submittedFormat': json['submitted_format'],
        'pages': !exists(json, 'pages') ? undefined : json['pages'],
        'keywords': !exists(json, 'keywords') ? undefined : json['keywords'],
        'boilerplate': json['boilerplate'],
        'stdLevel': json['std_level'],
        'publicationStdLevel': !exists(json, 'publication_std_level') ? undefined : json['publication_std_level'],
        'stream': json['stream'],
        'publicationStream': !exists(json, 'publication_stream') ? undefined : json['publication_stream'],
        'authors': ((json['authors'] as Array<any>).map(RfcAuthorFromJSON)),
        'shepherd': !exists(json, 'shepherd') ? undefined : BaseDatatrackerPersonFromJSON(json['shepherd']),
        'iesgContact': !exists(json, 'iesg_contact') ? undefined : BaseDatatrackerPersonFromJSON(json['iesg_contact']),
        'assignmentSet': !exists(json, 'assignment_set') ? undefined : ((json['assignment_set'] as Array<any>).map(AssignmentFromJSON)),
        'actionholderSet': !exists(json, 'actionholder_set') ? undefined : ((json['actionholder_set'] as Array<any>).map(ActionHolderFromJSON)),
        'pendingActivities': !exists(json, 'pending_activities') ? undefined : ((json['pending_activities'] as Array<any>).map(RpcRoleFromJSON)),
        'rfcNumber': !exists(json, 'rfc_number') ? undefined : json['rfc_number'],
        'publishedAt': !exists(json, 'published_at') ? undefined : (json['published_at'] === null ? null : new Date(json['published_at'])),
        'consensus': !exists(json, 'consensus') ? undefined : json['consensus'],
        'subseries': !exists(json, 'subseries') ? undefined : ((json['subseries'] as Array<any>).map(SubseriesMemberFromJSON)),
        'ianaStatus': !exists(json, 'iana_status') ? undefined : IanaStatusFromJSON(json['iana_status']),
    };
}

export function RfcToBeToJSON(value?: RfcToBe | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'abstract': value._abstract,
        'group': value.group,
        'disposition': value.disposition,
        'external_deadline': value.externalDeadline === undefined ? undefined : (value.externalDeadline === null ? null : value.externalDeadline.toISOString()),
        'internal_goal': value.internalGoal === undefined ? undefined : (value.internalGoal === null ? null : value.internalGoal.toISOString()),
        'labels': value.labels,
        'submitted_format': value.submittedFormat,
        'pages': value.pages,
        'keywords': value.keywords,
        'boilerplate': value.boilerplate,
        'std_level': value.stdLevel,
        'publication_std_level': value.publicationStdLevel,
        'stream': value.stream,
        'publication_stream': value.publicationStream,
        'authors': ((value.authors as Array<any>).map(RfcAuthorToJSON)),
        'rfc_number': value.rfcNumber,
        'consensus': value.consensus,
    };
}

