/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DatatrackerPerson } from './DatatrackerPerson';
import {
    DatatrackerPersonFromJSON,
    DatatrackerPersonFromJSONTyped,
    DatatrackerPersonToJSON,
} from './DatatrackerPerson';

/**
 * Serialize a HistoricalRecord
 * @export
 * @interface RfcToBeHistory
 */
export interface RfcToBeHistory {
    /**
     * 
     * @type {number}
     * @memberof RfcToBeHistory
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof RfcToBeHistory
     */
    time: Date;
    /**
     * 
     * @type {DatatrackerPerson}
     * @memberof RfcToBeHistory
     */
    by: DatatrackerPerson;
    /**
     * 
     * @type {string}
     * @memberof RfcToBeHistory
     */
    desc: string;
}

/**
 * Check if a given object implements the RfcToBeHistory interface.
 */
export function instanceOfRfcToBeHistory(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "time" in value;
    isInstance = isInstance && "by" in value;
    isInstance = isInstance && "desc" in value;

    return isInstance;
}

export function RfcToBeHistoryFromJSON(json: any): RfcToBeHistory {
    return RfcToBeHistoryFromJSONTyped(json, false);
}

export function RfcToBeHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RfcToBeHistory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'time': (new Date(json['time'])),
        'by': DatatrackerPersonFromJSON(json['by']),
        'desc': json['desc'],
    };
}

export function RfcToBeHistoryToJSON(value?: RfcToBeHistory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'time': (value.time.toISOString()),
        'by': DatatrackerPersonToJSON(value.by),
        'desc': value.desc,
    };
}

