/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlockingReason } from './BlockingReason';
import {
    BlockingReasonFromJSON,
    BlockingReasonFromJSONTyped,
    BlockingReasonToJSON,
} from './BlockingReason';

/**
 * Serialize RfcToBeBlockingReason with reason details
 * @export
 * @interface RfcToBeBlockingReason
 */
export interface RfcToBeBlockingReason {
    /**
     * 
     * @type {BlockingReason}
     * @memberof RfcToBeBlockingReason
     */
    readonly reason?: BlockingReason;
    /**
     * 
     * @type {Date}
     * @memberof RfcToBeBlockingReason
     */
    readonly sinceWhen?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RfcToBeBlockingReason
     */
    readonly resolved?: Date;
}

/**
 * Check if a given object implements the RfcToBeBlockingReason interface.
 */
export function instanceOfRfcToBeBlockingReason(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RfcToBeBlockingReasonFromJSON(json: any): RfcToBeBlockingReason {
    return RfcToBeBlockingReasonFromJSONTyped(json, false);
}

export function RfcToBeBlockingReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): RfcToBeBlockingReason {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reason': !exists(json, 'reason') ? undefined : BlockingReasonFromJSON(json['reason']),
        'sinceWhen': !exists(json, 'since_when') ? undefined : (new Date(json['since_when'])),
        'resolved': !exists(json, 'resolved') ? undefined : (new Date(json['resolved'])),
    };
}

export function RfcToBeBlockingReasonToJSON(value?: RfcToBeBlockingReason | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

