/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IanaStatusSlugEnum } from './IanaStatusSlugEnum';
import {
    IanaStatusSlugEnumFromJSON,
    IanaStatusSlugEnumFromJSONTyped,
    IanaStatusSlugEnumToJSON,
} from './IanaStatusSlugEnum';
import type { RfcAuthorRequest } from './RfcAuthorRequest';
import {
    RfcAuthorRequestFromJSON,
    RfcAuthorRequestFromJSONTyped,
    RfcAuthorRequestToJSON,
} from './RfcAuthorRequest';

/**
 * RfcToBeSerializer suitable for displaying full details of a single instance
 * @export
 * @interface RfcToBeRequest
 */
export interface RfcToBeRequest {
    /**
     * Document title
     * @type {string}
     * @memberof RfcToBeRequest
     */
    title: string;
    /**
     * Document abstract
     * @type {string}
     * @memberof RfcToBeRequest
     */
    _abstract?: string;
    /**
     * Acronym of datatracker group where this document originated, if any
     * @type {string}
     * @memberof RfcToBeRequest
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof RfcToBeRequest
     */
    disposition: string;
    /**
     * 
     * @type {Date}
     * @memberof RfcToBeRequest
     */
    externalDeadline?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RfcToBeRequest
     */
    internalGoal?: Date | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof RfcToBeRequest
     */
    labels: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof RfcToBeRequest
     */
    submittedFormat: string;
    /**
     * Page count
     * @type {number}
     * @memberof RfcToBeRequest
     */
    pages?: number | null;
    /**
     * Comma-separated list of keywords
     * @type {string}
     * @memberof RfcToBeRequest
     */
    keywords?: string;
    /**
     * TLP IPR boilerplate option
     * @type {string}
     * @memberof RfcToBeRequest
     */
    boilerplate: string;
    /**
     * Current StdLevel
     * @type {string}
     * @memberof RfcToBeRequest
     */
    stdLevel: string;
    /**
     * StdLevel at publication (blank until published)
     * @type {string}
     * @memberof RfcToBeRequest
     */
    publicationStdLevel?: string | null;
    /**
     * Current stream
     * @type {string}
     * @memberof RfcToBeRequest
     */
    stream: string;
    /**
     * Stream at publication (blank until published)
     * @type {string}
     * @memberof RfcToBeRequest
     */
    publicationStream?: string | null;
    /**
     * 
     * @type {Array<RfcAuthorRequest>}
     * @memberof RfcToBeRequest
     */
    authors: Array<RfcAuthorRequest>;
    /**
     * 
     * @type {number}
     * @memberof RfcToBeRequest
     */
    rfcNumber?: number | null;
    /**
     * Whether document has consensus (None=unknown)
     * @type {boolean}
     * @memberof RfcToBeRequest
     */
    consensus?: boolean | null;
    /**
     * 
     * @type {IanaStatusSlugEnum}
     * @memberof RfcToBeRequest
     */
    ianaStatusSlug?: IanaStatusSlugEnum;
}

/**
 * Check if a given object implements the RfcToBeRequest interface.
 */
export function instanceOfRfcToBeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "disposition" in value;
    isInstance = isInstance && "labels" in value;
    isInstance = isInstance && "submittedFormat" in value;
    isInstance = isInstance && "boilerplate" in value;
    isInstance = isInstance && "stdLevel" in value;
    isInstance = isInstance && "stream" in value;
    isInstance = isInstance && "authors" in value;

    return isInstance;
}

export function RfcToBeRequestFromJSON(json: any): RfcToBeRequest {
    return RfcToBeRequestFromJSONTyped(json, false);
}

export function RfcToBeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RfcToBeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        '_abstract': !exists(json, 'abstract') ? undefined : json['abstract'],
        'group': !exists(json, 'group') ? undefined : json['group'],
        'disposition': json['disposition'],
        'externalDeadline': !exists(json, 'external_deadline') ? undefined : (json['external_deadline'] === null ? null : new Date(json['external_deadline'])),
        'internalGoal': !exists(json, 'internal_goal') ? undefined : (json['internal_goal'] === null ? null : new Date(json['internal_goal'])),
        'labels': json['labels'],
        'submittedFormat': json['submitted_format'],
        'pages': !exists(json, 'pages') ? undefined : json['pages'],
        'keywords': !exists(json, 'keywords') ? undefined : json['keywords'],
        'boilerplate': json['boilerplate'],
        'stdLevel': json['std_level'],
        'publicationStdLevel': !exists(json, 'publication_std_level') ? undefined : json['publication_std_level'],
        'stream': json['stream'],
        'publicationStream': !exists(json, 'publication_stream') ? undefined : json['publication_stream'],
        'authors': ((json['authors'] as Array<any>).map(RfcAuthorRequestFromJSON)),
        'rfcNumber': !exists(json, 'rfc_number') ? undefined : json['rfc_number'],
        'consensus': !exists(json, 'consensus') ? undefined : json['consensus'],
        'ianaStatusSlug': !exists(json, 'iana_status_slug') ? undefined : IanaStatusSlugEnumFromJSON(json['iana_status_slug']),
    };
}

export function RfcToBeRequestToJSON(value?: RfcToBeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'abstract': value._abstract,
        'group': value.group,
        'disposition': value.disposition,
        'external_deadline': value.externalDeadline === undefined ? undefined : (value.externalDeadline === null ? null : value.externalDeadline.toISOString()),
        'internal_goal': value.internalGoal === undefined ? undefined : (value.internalGoal === null ? null : value.internalGoal.toISOString()),
        'labels': value.labels,
        'submitted_format': value.submittedFormat,
        'pages': value.pages,
        'keywords': value.keywords,
        'boilerplate': value.boilerplate,
        'std_level': value.stdLevel,
        'publication_std_level': value.publicationStdLevel,
        'stream': value.stream,
        'publication_stream': value.publicationStream,
        'authors': ((value.authors as Array<any>).map(RfcAuthorRequestToJSON)),
        'rfc_number': value.rfcNumber,
        'consensus': value.consensus,
        'iana_status_slug': IanaStatusSlugEnumToJSON(value.ianaStatusSlug),
    };
}

