/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Capability } from './Capability';
import {
    CapabilityFromJSON,
    CapabilityFromJSONTyped,
    CapabilityToJSON,
} from './Capability';
import type { RpcRole } from './RpcRole';
import {
    RpcRoleFromJSON,
    RpcRoleFromJSONTyped,
    RpcRoleToJSON,
} from './RpcRole';

/**
 * Serialize an RpcPerson
 * 
 * To avoid datatracker API calls, use the `name_map` parameter to
 * pass a dict mapping datatracker Person ID to name (designed for use
 * with the `get_persons()` API endpoint).
 * @export
 * @interface RpcPerson
 */
export interface RpcPerson {
    /**
     * 
     * @type {number}
     * @memberof RpcPerson
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof RpcPerson
     */
    readonly name?: string;
    /**
     * 
     * @type {number}
     * @memberof RpcPerson
     */
    hoursPerWeek?: number;
    /**
     * 
     * @type {Array<Capability>}
     * @memberof RpcPerson
     */
    capabilities: Array<Capability>;
    /**
     * 
     * @type {Array<RpcRole>}
     * @memberof RpcPerson
     */
    roles: Array<RpcRole>;
    /**
     * 
     * @type {boolean}
     * @memberof RpcPerson
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RpcPerson
     */
    readonly email?: string;
    /**
     * 
     * @type {string}
     * @memberof RpcPerson
     */
    readonly picture?: string;
    /**
     * 
     * @type {string}
     * @memberof RpcPerson
     */
    readonly datatrackerUrl?: string;
}

/**
 * Check if a given object implements the RpcPerson interface.
 */
export function instanceOfRpcPerson(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "capabilities" in value;
    isInstance = isInstance && "roles" in value;

    return isInstance;
}

export function RpcPersonFromJSON(json: any): RpcPerson {
    return RpcPersonFromJSONTyped(json, false);
}

export function RpcPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcPerson {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'hoursPerWeek': !exists(json, 'hours_per_week') ? undefined : json['hours_per_week'],
        'capabilities': ((json['capabilities'] as Array<any>).map(CapabilityFromJSON)),
        'roles': ((json['roles'] as Array<any>).map(RpcRoleFromJSON)),
        'isActive': !exists(json, 'is_active') ? undefined : json['is_active'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'picture': !exists(json, 'picture') ? undefined : json['picture'],
        'datatrackerUrl': !exists(json, 'datatracker_url') ? undefined : json['datatracker_url'],
    };
}

export function RpcPersonToJSON(value?: RpcPerson | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hours_per_week': value.hoursPerWeek,
        'capabilities': ((value.capabilities as Array<any>).map(CapabilityToJSON)),
        'roles': ((value.roles as Array<any>).map(RpcRoleToJSON)),
        'is_active': value.isActive,
    };
}

