/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for related document for an RfcToBe
 * @export
 * @interface RpcRelatedDocument
 */
export interface RpcRelatedDocument {
    /**
     * 
     * @type {number}
     * @memberof RpcRelatedDocument
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof RpcRelatedDocument
     */
    relationship: string;
    /**
     * 
     * @type {string}
     * @memberof RpcRelatedDocument
     */
    readonly draftName?: string;
    /**
     * 
     * @type {string}
     * @memberof RpcRelatedDocument
     */
    readonly targetDraftName?: string;
}

/**
 * Check if a given object implements the RpcRelatedDocument interface.
 */
export function instanceOfRpcRelatedDocument(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "relationship" in value;

    return isInstance;
}

export function RpcRelatedDocumentFromJSON(json: any): RpcRelatedDocument {
    return RpcRelatedDocumentFromJSONTyped(json, false);
}

export function RpcRelatedDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcRelatedDocument {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'relationship': json['relationship'],
        'draftName': !exists(json, 'draft_name') ? undefined : json['draft_name'],
        'targetDraftName': !exists(json, 'target_draft_name') ? undefined : json['target_draft_name'],
    };
}

export function RpcRelatedDocumentToJSON(value?: RpcRelatedDocument | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'relationship': value.relationship,
    };
}

