/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcRole
 */
export interface RpcRole {
    /**
     * 
     * @type {string}
     * @memberof RpcRole
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof RpcRole
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RpcRole
     */
    desc?: string;
}

/**
 * Check if a given object implements the RpcRole interface.
 */
export function instanceOfRpcRole(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function RpcRoleFromJSON(json: any): RpcRole {
    return RpcRoleFromJSONTyped(json, false);
}

export function RpcRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'name': json['name'],
        'desc': !exists(json, 'desc') ? undefined : json['desc'],
    };
}

export function RpcRoleToJSON(value?: RpcRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
        'desc': value.desc,
    };
}

