/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for related document for an RfcToBe
 * @export
 * @interface RpcRelatedDocumentRequest
 */
export interface RpcRelatedDocumentRequest {
    /**
     * 
     * @type {string}
     * @memberof RpcRelatedDocumentRequest
     */
    relationship: string;
}

/**
 * Check if a given object implements the RpcRelatedDocumentRequest interface.
 */
export function instanceOfRpcRelatedDocumentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "relationship" in value;

    return isInstance;
}

export function RpcRelatedDocumentRequestFromJSON(json: any): RpcRelatedDocumentRequest {
    return RpcRelatedDocumentRequestFromJSONTyped(json, false);
}

export function RpcRelatedDocumentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcRelatedDocumentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'relationship': json['relationship'],
    };
}

export function RpcRelatedDocumentRequestToJSON(value?: RpcRelatedDocumentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'relationship': value.relationship,
    };
}

