/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a cluster without its contents
 * @export
 * @interface SimpleCluster
 */
export interface SimpleCluster {
    /**
     * 
     * @type {number}
     * @memberof SimpleCluster
     */
    number: number;
}

/**
 * Check if a given object implements the SimpleCluster interface.
 */
export function instanceOfSimpleCluster(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;

    return isInstance;
}

export function SimpleClusterFromJSON(json: any): SimpleCluster {
    return SimpleClusterFromJSONTyped(json, false);
}

export function SimpleClusterFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleCluster {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': json['number'],
    };
}

export function SimpleClusterToJSON(value?: SimpleCluster | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
    };
}

