/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a cluster without its contents
 * @export
 * @interface SimpleClusterRequest
 */
export interface SimpleClusterRequest {
    /**
     * 
     * @type {number}
     * @memberof SimpleClusterRequest
     */
    number: number;
}

/**
 * Check if a given object implements the SimpleClusterRequest interface.
 */
export function instanceOfSimpleClusterRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;

    return isInstance;
}

export function SimpleClusterRequestFromJSON(json: any): SimpleClusterRequest {
    return SimpleClusterRequestFromJSONTyped(json, false);
}

export function SimpleClusterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleClusterRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': json['number'],
    };
}

export function SimpleClusterRequestToJSON(value?: SimpleClusterRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
    };
}

