/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `assigned` - Assigned
 * * `in_progress` - In Progress
 * * `done` - Done
 * * `withdrawn` - Withdrawn
 * * `closed_for_hold` - Closed For Hold
 * @export
 */
export const StateEnum = {
    Assigned: 'assigned',
    InProgress: 'in_progress',
    Done: 'done',
    Withdrawn: 'withdrawn',
    ClosedForHold: 'closed_for_hold'
} as const;
export type StateEnum = typeof StateEnum[keyof typeof StateEnum];


export function StateEnumFromJSON(json: any): StateEnum {
    return StateEnumFromJSONTyped(json, false);
}

export function StateEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateEnum {
    return json as StateEnum;
}

export function StateEnumToJSON(value?: StateEnum | null): any {
    return value as any;
}

