/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Name } from './Name';
import {
    NameFromJSON,
    NameFromJSONTyped,
    NameToJSON,
} from './Name';
import type { SubmissionAuthor } from './SubmissionAuthor';
import {
    SubmissionAuthorFromJSON,
    SubmissionAuthorFromJSONTyped,
    SubmissionAuthorToJSON,
} from './SubmissionAuthor';

/**
 * Serialize a submission
 * @export
 * @interface Submission
 */
export interface Submission {
    /**
     * 
     * @type {number}
     * @memberof Submission
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    rev: string;
    /**
     * 
     * @type {Name}
     * @memberof Submission
     */
    stream: Name;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof Submission
     */
    pages: number;
    /**
     * 
     * @type {Name}
     * @memberof Submission
     */
    sourceFormat: Name;
    /**
     * 
     * @type {Array<SubmissionAuthor>}
     * @memberof Submission
     */
    authors: Array<SubmissionAuthor>;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    shepherd: string;
    /**
     * 
     * @type {Name}
     * @memberof Submission
     */
    stdLevel?: Name;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    datatrackerUrl: string;
    /**
     * 
     * @type {boolean}
     * @memberof Submission
     */
    consensus: boolean;
}

/**
 * Check if a given object implements the Submission interface.
 */
export function instanceOfSubmission(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "rev" in value;
    isInstance = isInstance && "stream" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "pages" in value;
    isInstance = isInstance && "sourceFormat" in value;
    isInstance = isInstance && "authors" in value;
    isInstance = isInstance && "shepherd" in value;
    isInstance = isInstance && "datatrackerUrl" in value;
    isInstance = isInstance && "consensus" in value;

    return isInstance;
}

export function SubmissionFromJSON(json: any): Submission {
    return SubmissionFromJSONTyped(json, false);
}

export function SubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Submission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'rev': json['rev'],
        'stream': NameFromJSON(json['stream']),
        'title': json['title'],
        'pages': json['pages'],
        'sourceFormat': NameFromJSON(json['source_format']),
        'authors': ((json['authors'] as Array<any>).map(SubmissionAuthorFromJSON)),
        'shepherd': json['shepherd'],
        'stdLevel': !exists(json, 'std_level') ? undefined : NameFromJSON(json['std_level']),
        'datatrackerUrl': json['datatracker_url'],
        'consensus': json['consensus'],
    };
}

export function SubmissionToJSON(value?: Submission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'rev': value.rev,
        'stream': NameToJSON(value.stream),
        'title': value.title,
        'pages': value.pages,
        'source_format': NameToJSON(value.sourceFormat),
        'authors': ((value.authors as Array<any>).map(SubmissionAuthorToJSON)),
        'shepherd': value.shepherd,
        'std_level': NameToJSON(value.stdLevel),
        'datatracker_url': value.datatrackerUrl,
        'consensus': value.consensus,
    };
}

