/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmissionAuthor
 */
export interface SubmissionAuthor {
    /**
     * 
     * @type {number}
     * @memberof SubmissionAuthor
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SubmissionAuthor
     */
    plainName: string;
}

/**
 * Check if a given object implements the SubmissionAuthor interface.
 */
export function instanceOfSubmissionAuthor(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "plainName" in value;

    return isInstance;
}

export function SubmissionAuthorFromJSON(json: any): SubmissionAuthor {
    return SubmissionAuthorFromJSONTyped(json, false);
}

export function SubmissionAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionAuthor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'plainName': json['plain_name'],
    };
}

export function SubmissionAuthorToJSON(value?: SubmissionAuthor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'plain_name': value.plainName,
    };
}

