/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a submission list item
 * 
 * Only includes a subset of the SubmissionSerializer fields
 * @export
 * @interface SubmissionListItem
 */
export interface SubmissionListItem {
    /**
     * 
     * @type {number}
     * @memberof SubmissionListItem
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SubmissionListItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SubmissionListItem
     */
    stream: string;
    /**
     * 
     * @type {Date}
     * @memberof SubmissionListItem
     */
    submitted: Date;
}

/**
 * Check if a given object implements the SubmissionListItem interface.
 */
export function instanceOfSubmissionListItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "stream" in value;
    isInstance = isInstance && "submitted" in value;

    return isInstance;
}

export function SubmissionListItemFromJSON(json: any): SubmissionListItem {
    return SubmissionListItemFromJSONTyped(json, false);
}

export function SubmissionListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'stream': json['stream'],
        'submitted': (new Date(json['submitted'])),
    };
}

export function SubmissionListItemToJSON(value?: SubmissionListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'stream': value.stream,
        'submitted': (value.submitted.toISOString()),
    };
}

