/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubseriesTypeName
 */
export interface SubseriesTypeName {
    /**
     * 
     * @type {string}
     * @memberof SubseriesTypeName
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof SubseriesTypeName
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SubseriesTypeName
     */
    desc?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SubseriesTypeName
     */
    used?: boolean;
}

/**
 * Check if a given object implements the SubseriesTypeName interface.
 */
export function instanceOfSubseriesTypeName(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function SubseriesTypeNameFromJSON(json: any): SubseriesTypeName {
    return SubseriesTypeNameFromJSONTyped(json, false);
}

export function SubseriesTypeNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubseriesTypeName {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'name': json['name'],
        'desc': !exists(json, 'desc') ? undefined : json['desc'],
        'used': !exists(json, 'used') ? undefined : json['used'],
    };
}

export function SubseriesTypeNameToJSON(value?: SubseriesTypeName | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
        'desc': value.desc,
        'used': value.used,
    };
}

