/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a SubseriesMember
 * @export
 * @interface SubseriesMember
 */
export interface SubseriesMember {
    /**
     * 
     * @type {number}
     * @memberof SubseriesMember
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof SubseriesMember
     */
    rfcToBe: number;
    /**
     * 
     * @type {string}
     * @memberof SubseriesMember
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof SubseriesMember
     */
    number: number;
    /**
     * 
     * @type {string}
     * @memberof SubseriesMember
     */
    readonly displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof SubseriesMember
     */
    readonly slug?: string;
}

/**
 * Check if a given object implements the SubseriesMember interface.
 */
export function instanceOfSubseriesMember(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rfcToBe" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "number" in value;

    return isInstance;
}

export function SubseriesMemberFromJSON(json: any): SubseriesMember {
    return SubseriesMemberFromJSONTyped(json, false);
}

export function SubseriesMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubseriesMember {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'rfcToBe': json['rfc_to_be'],
        'type': json['type'],
        'number': json['number'],
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
    };
}

export function SubseriesMemberToJSON(value?: SubseriesMember | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rfc_to_be': value.rfcToBe,
        'type': value.type,
        'number': value.number,
    };
}

