/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize a SubseriesMember
 * @export
 * @interface SubseriesMemberRequest
 */
export interface SubseriesMemberRequest {
    /**
     * 
     * @type {number}
     * @memberof SubseriesMemberRequest
     */
    rfcToBe: number;
    /**
     * 
     * @type {string}
     * @memberof SubseriesMemberRequest
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof SubseriesMemberRequest
     */
    number: number;
}

/**
 * Check if a given object implements the SubseriesMemberRequest interface.
 */
export function instanceOfSubseriesMemberRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rfcToBe" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "number" in value;

    return isInstance;
}

export function SubseriesMemberRequestFromJSON(json: any): SubseriesMemberRequest {
    return SubseriesMemberRequestFromJSONTyped(json, false);
}

export function SubseriesMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubseriesMemberRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rfcToBe': json['rfc_to_be'],
        'type': json['type'],
        'number': json['number'],
    };
}

export function SubseriesMemberRequestToJSON(value?: SubseriesMemberRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rfc_to_be': value.rfcToBe,
        'type': value.type,
        'number': value.number,
    };
}

