/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MinimalRfcToBe } from './MinimalRfcToBe';
import {
    MinimalRfcToBeFromJSON,
    MinimalRfcToBeFromJSONTyped,
    MinimalRfcToBeToJSON,
} from './MinimalRfcToBe';

/**
 * 
 * @export
 * @interface SubseriesDoc
 */
export interface SubseriesDoc {
    /**
     * 
     * @type {string}
     * @memberof SubseriesDoc
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof SubseriesDoc
     */
    number: number;
    /**
     * 
     * @type {Array<MinimalRfcToBe>}
     * @memberof SubseriesDoc
     */
    documents: Array<MinimalRfcToBe>;
    /**
     * 
     * @type {number}
     * @memberof SubseriesDoc
     */
    readonly rfcCount?: number;
    /**
     * 
     * @type {string}
     * @memberof SubseriesDoc
     */
    readonly slug?: string;
    /**
     * 
     * @type {string}
     * @memberof SubseriesDoc
     */
    readonly displayName?: string;
}

/**
 * Check if a given object implements the SubseriesDoc interface.
 */
export function instanceOfSubseriesDoc(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "number" in value;
    isInstance = isInstance && "documents" in value;

    return isInstance;
}

export function SubseriesDocFromJSON(json: any): SubseriesDoc {
    return SubseriesDocFromJSONTyped(json, false);
}

export function SubseriesDocFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubseriesDoc {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'number': json['number'],
        'documents': ((json['documents'] as Array<any>).map(MinimalRfcToBeFromJSON)),
        'rfcCount': !exists(json, 'rfc_count') ? undefined : json['rfc_count'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'displayName': !exists(json, 'display_name') ? undefined : json['display_name'],
    };
}

export function SubseriesDocToJSON(value?: SubseriesDoc | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'number': value.number,
        'documents': ((value.documents as Array<any>).map(MinimalRfcToBeToJSON)),
    };
}

