/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncMetadataRequestRequest
 */
export interface SyncMetadataRequestRequest {
    /**
     * Git commit SHA identifying the metadata result
     * @type {string}
     * @memberof SyncMetadataRequestRequest
     */
    headSha: string;
}

/**
 * Check if a given object implements the SyncMetadataRequestRequest interface.
 */
export function instanceOfSyncMetadataRequestRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "headSha" in value;

    return isInstance;
}

export function SyncMetadataRequestRequestFromJSON(json: any): SyncMetadataRequestRequest {
    return SyncMetadataRequestRequestFromJSONTyped(json, false);
}

export function SyncMetadataRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncMetadataRequestRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'headSha': json['head_sha'],
    };
}

export function SyncMetadataRequestRequestToJSON(value?: SyncMetadataRequestRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'head_sha': value.headSha,
    };
}

