/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncMetadataNotFoundResponse
 */
export interface SyncMetadataNotFoundResponse {
    /**
     * 
     * @type {string}
     * @memberof SyncMetadataNotFoundResponse
     */
    error: string;
}

/**
 * Check if a given object implements the SyncMetadataNotFoundResponse interface.
 */
export function instanceOfSyncMetadataNotFoundResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function SyncMetadataNotFoundResponseFromJSON(json: any): SyncMetadataNotFoundResponse {
    return SyncMetadataNotFoundResponseFromJSONTyped(json, false);
}

export function SyncMetadataNotFoundResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncMetadataNotFoundResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function SyncMetadataNotFoundResponseToJSON(value?: SyncMetadataNotFoundResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

