/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncMetadataBadRequestResponse
 */
export interface SyncMetadataBadRequestResponse {
    /**
     * 
     * @type {string}
     * @memberof SyncMetadataBadRequestResponse
     */
    error: string;
}

/**
 * Check if a given object implements the SyncMetadataBadRequestResponse interface.
 */
export function instanceOfSyncMetadataBadRequestResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function SyncMetadataBadRequestResponseFromJSON(json: any): SyncMetadataBadRequestResponse {
    return SyncMetadataBadRequestResponseFromJSONTyped(json, false);
}

export function SyncMetadataBadRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncMetadataBadRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function SyncMetadataBadRequestResponseToJSON(value?: SyncMetadataBadRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

