/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize an Unusable Rfc Number
 * @export
 * @interface UnusableRfcNumber
 */
export interface UnusableRfcNumber {
    /**
     * 
     * @type {number}
     * @memberof UnusableRfcNumber
     */
    number: number;
    /**
     * 
     * @type {string}
     * @memberof UnusableRfcNumber
     */
    comment?: string;
    /**
     * 
     * @type {Date}
     * @memberof UnusableRfcNumber
     */
    readonly createdAt?: Date;
}

/**
 * Check if a given object implements the UnusableRfcNumber interface.
 */
export function instanceOfUnusableRfcNumber(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;

    return isInstance;
}

export function UnusableRfcNumberFromJSON(json: any): UnusableRfcNumber {
    return UnusableRfcNumberFromJSONTyped(json, false);
}

export function UnusableRfcNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnusableRfcNumber {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': json['number'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
    };
}

export function UnusableRfcNumberToJSON(value?: UnusableRfcNumber | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'comment': value.comment,
    };
}

