/* tslint:disable */
/* eslint-disable */
/**
 * Purple
 * Backend API for the Purple app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serialize an Unusable Rfc Number
 * @export
 * @interface UnusableRfcNumberRequest
 */
export interface UnusableRfcNumberRequest {
    /**
     * 
     * @type {number}
     * @memberof UnusableRfcNumberRequest
     */
    number: number;
    /**
     * 
     * @type {string}
     * @memberof UnusableRfcNumberRequest
     */
    comment?: string;
}

/**
 * Check if a given object implements the UnusableRfcNumberRequest interface.
 */
export function instanceOfUnusableRfcNumberRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "number" in value;

    return isInstance;
}

export function UnusableRfcNumberRequestFromJSON(json: any): UnusableRfcNumberRequest {
    return UnusableRfcNumberRequestFromJSONTyped(json, false);
}

export function UnusableRfcNumberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnusableRfcNumberRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': json['number'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
    };
}

export function UnusableRfcNumberRequestToJSON(value?: UnusableRfcNumberRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'comment': value.comment,
    };
}

