name: Build K8s Images
on:
  workflow_dispatch:
    inputs:
      datatrackerRef:
        description: 'Datatracker API Spec Repo Ref'
        required: true
        type: string
        default: 'main'
      deploy:
        description: 'Deploy to K8S'
        default: 'Skip'
        required: true
        type: choice
        options:
          - Skip
          - Staging Only
          - Staging + Demo
          - Staging + Prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      pkg_version: ${{ steps.buildvars.outputs.pkg_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          fetch-tags: false
          path: purple

      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          fetch-tags: false
          repository: ietf-tools/datatracker
          ref: ${{ inputs.datatrackerRef }}
          path: datatracker

      - name: Get Next Version
        id: semver
        if: ${{ inputs.deploy == 'Staging Only' || inputs.deploy == 'Staging + Demo' || inputs.deploy == 'Staging + Prod' }}
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          skipInvalidTags: true
          patchList: fix, bugfix, perf, refactor, test, tests, chore

      - name: Get Dev Version
        if: ${{ inputs.deploy == 'Skip' }}
        id: semverdev
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          skipInvalidTags: true
          noVersionBumpBehavior: 'current'
          noNewCommitBehavior: 'current'

      - name: Set Release Flag
        if: ${{ inputs.deploy == 'Staging Only' || inputs.deploy == 'Staging + Demo' || inputs.deploy == 'Staging + Prod' }}
        run: |
          echo "IS_RELEASE=true" >> $GITHUB_ENV

      - name: Set Build Variables
        id: buildvars
        run: |
          if [[ $IS_RELEASE ]]; then
            echo "Using AUTO SEMVER mode: ${{ steps.semver.outputs.nextStrict }}"
            echo "pkg_version=${{ steps.semver.outputs.nextStrict }}" >> $GITHUB_OUTPUT
            echo "::notice::Release ${{ steps.semver.outputs.nextStrict }} created using branch $GITHUB_REF_NAME"
          else
            echo "Using DEV mode: ${{ steps.semverdev.outputs.nextMajorStrict }}.0.0-dev.$GITHUB_RUN_NUMBER"
            echo "pkg_version=${{ steps.semverdev.outputs.nextMajorStrict }}.0.0-dev.$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT
            echo "::notice::Non-production build ${{ steps.semverdev.outputs.nextMajorStrict }}.0.0-dev.$GITHUB_RUN_NUMBER created using branch $GITHUB_REF_NAME"
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Datatracker API spec
        working-directory: ./datatracker
        run: |
          cat > doit.bash <<EOF
          echo "Creating and activating virtual environment..."
          python -mvenv venv
          source venv/bin/activate
          echo "Installing requirements..."
          pip install -r requirements.txt
          echo "Generating OpenAPI spec..."
          touch ietf/settings_local.py
          ietf/manage.py spectacular --skip-checks --file rpcapi.yaml
          EOF
          docker run --rm --volume .:/workspace ghcr.io/ietf-tools/datatracker-app-base:latest /bin/bash -e doit.bash
          mv rpcapi.yaml ..

      - name: Install dependencies
        run: npm ci
        working-directory: ./purple/client

      - name: Generate Datatracker API client
        working-directory: ./purple
        run: |
          cp ../rpcapi.yaml .
          npx --yes @openapitools/openapi-generator-cli@2.29 generate --generator-key datatracker
          tar cfz ../rpcapi_client.tgz -C openapi rpcapi_client

      - name: Build backend image
        uses: docker/build-push-action@v7
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: ./purple
          file: ./purple/dev/build/backend.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ietf-tools/purple-backend:${{ steps.buildvars.outputs.pkg_version }}
            ghcr.io/ietf-tools/purple-backend:latest

      - name: Build statics image
        uses: docker/build-push-action@v7
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: ./purple
          file: ./purple/dev/build/statics.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ietf-tools/purple-statics:${{ steps.buildvars.outputs.pkg_version }}
            ghcr.io/ietf-tools/purple-statics:latest

      - name: Generate Purple API client
        working-directory: ./purple
        run: |
          container_id="$(docker create ghcr.io/ietf-tools/purple-backend:latest)"
          docker cp "${container_id}:/workspace/purple_api.yaml" ./
          docker rm "${container_id}"
          npx --yes @openapitools/openapi-generator-cli@2.29 generate --generator-key purple
          tar cfz ../purple_client.tgz -C client/app purple_client
          cp purple_api.yaml ..

      - name: Upload API
        uses: actions/upload-artifact@v7
        with:
          name: api-clients
          path: |
            purple_api.yaml
            rpcapi.yaml
            purple_client.tgz
            rpcapi_client.tgz

      - name: Build frontend image
        uses: docker/build-push-action@v7
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: ./purple
          file: ./purple/dev/build/frontend.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ietf-tools/purple-frontend:${{ steps.buildvars.outputs.pkg_version }}
            ghcr.io/ietf-tools/purple-frontend:latest

      - name: Create Draft Release
        if: ${{ env.IS_RELEASE == 'true' }}
        uses: ncipollo/release-action@v1.21.0
        with:
          prerelease: true
          draft: false
          owner: ietf-tools
          repo: purple
          commit: ${{ github.sha }}
          tag: ${{ steps.semver.outputs.nextStrict }}
          name: ${{ steps.semver.outputs.nextStrict }}
          body: '*pending*'
          token: ${{ github.token }}

      - name: Generate CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1
        if: ${{ env.IS_RELEASE == 'true' }}
        with:
          token: ${{ github.token }}
          fromTag: ${{ steps.semver.outputs.nextStrict }}
          toTag: ${{ steps.semver.outputs.current }}
          writeToFile: false

      - name: Finalize Release
        if: ${{ env.IS_RELEASE == 'true' }}
        uses: ncipollo/release-action@v1.21.0
        with:
          allowUpdates: true
          makeLatest: true
          draft: false
          owner: ietf-tools
          repo: purple
          tag: ${{ steps.semver.outputs.nextStrict }}
          name: ${{ steps.semver.outputs.nextStrict }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

  # -----------------------------------------------------------------
  # STAGING
  # -----------------------------------------------------------------
  staging:
    name: Deploy to Staging
    if: ${{ !failure() && !cancelled() && (inputs.deploy == 'Staging Only' || inputs.deploy == 'Staging + Demo' || inputs.deploy == 'Staging + Prod') }}
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: staging
    env:
      PKG_VERSION: ${{needs.build.outputs.pkg_version}}

    steps:
      - name: Deploy to staging
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: deploy.yml
          repo: ietf-tools/infra-k8s
          ref: main
          token: ${{ secrets.GH_INFRA_K8S_TOKEN }}
          inputs: '{ "environment":"${{ secrets.GHA_K8S_CLUSTER }}", "app":"purple", "appVersion":"${{ env.PKG_VERSION }}", "remoteRef":"${{ github.sha }}" }'
          wait-for-completion: true
          wait-for-completion-timeout: 10m
          wait-for-completion-interval: 30s
          display-workflow-run-url: false

  # -----------------------------------------------------------------
  # DEMO
  # -----------------------------------------------------------------
  demo:
    name: Deploy to Demo
    if: ${{ !failure() && !cancelled() && (inputs.deploy == 'Staging + Demo') }}
    needs: [build, staging]
    runs-on: ubuntu-latest
    environment:
      name: demo
    env:
      PKG_VERSION: ${{needs.build.outputs.pkg_version}}

    steps:
      - name: Deploy to staging
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: deploy.yml
          repo: ietf-tools/infra-k8s
          ref: main
          token: ${{ secrets.GH_INFRA_K8S_TOKEN }}
          inputs: '{ "environment":"${{ secrets.GHA_K8S_CLUSTER }}", "app":"purple", "appVersion":"${{ env.PKG_VERSION }}", "remoteRef":"${{ github.sha }}" }'
          wait-for-completion: true
          wait-for-completion-timeout: 10m
          wait-for-completion-interval: 30s
          display-workflow-run-url: false

  # -----------------------------------------------------------------
  # PROD
  # -----------------------------------------------------------------
  prod:
    name: Deploy to Production
    if: ${{ !failure() && !cancelled() && (inputs.deploy == 'Staging + Prod') }}
    needs: [build, staging]
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      PKG_VERSION: ${{needs.build.outputs.pkg_version}}

    steps:
      - name: Deploy to production
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: deploy.yml
          repo: ietf-tools/infra-k8s
          ref: main
          token: ${{ secrets.GH_INFRA_K8S_TOKEN }}
          inputs: '{ "environment":"${{ secrets.GHA_K8S_CLUSTER }}", "app":"purple", "appVersion":"${{ env.PKG_VERSION }}", "remoteRef":"${{ github.sha }}" }'
          wait-for-completion: true
          wait-for-completion-timeout: 10m
          wait-for-completion-interval: 30s
          display-workflow-run-url: false
